### ISSUE TITLE
(is-empty-tree? (leaf '()))의 결과도 #t인가요?

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#10]
분명히 (leaf '())와 (node '())의 결과는 다른 것이라고 생각되는데요,
(leaf '()) 또한 tree는 tree입니다. 그렇다면 (is-empty-tree?) 함수의 인자가 될 수 있다는 것인데, 이 경우에는 빈 나무라고 고려하나요?
또한 그렇다면 (is-empty-tree? (node (node '())))의 결과 역시 #t인지 궁금합니다.

**Comment by iKoru** [comment]
질문이 잘못되었네요. (is-empty-tree? (node (list (node '()) (node '()))))의 결과 역시 #t인지 궁금합니다.

**Comment by esifea** [comment]
(is-empty-tree? (node (list (node '()) (node '())))) 의 결과는 #f 입니다. 이에 따라 나머지 경우도 고려하시면 될 것 같습니다.

**Comment by iKoru** [comment]
@SanghoonPark 그렇다면 "빈 나무" 의 기준이 정확히 무엇인가요? 오직 (node '())만 "빈 나무"인가요?

**Comment by kim-yoonseung** [comment]
(node '()) 만 빈 나무입니다.
