### ISSUE TITLE
5-5 잘못된 타입

### ISSUE THREAD

**Issue by taehwoi** [snu-sf-class/PP2015f_TA#101]
안녕하세요.
 hw5-5.rkt의 뼈대코드에는 `equal`의 형이 form \* form -> form으로 되어 있지만 문제에 따르면 form \* form -> bool이 되어야 할 것 같습니다.
수정해주시면 감사하겠습니다.

**Comment by kim-yoonseung** [comment]
주석에 오타가 있군요. 수정하였습니다.

숙제 문서를 보고 숙제를 이미 하신 분들은 크게 신경쓰지 않으셔도 될 것 같습니다.
