### ISSUE TITLE
type-safe 관련 질문입니다.

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#102]
5-1, 5-2에서 type-safe하다는 것의 효용성?을 잘 모르겠습니다. 문제를 보면 타입에 맞게 들어온 모든 입력에 대해 안전하게 타입에 맞는 값을 반환해야 한다고 쓰여져 있는데, 실제로 저희가 라켓 프로그래밍을 할 때 항상 이와 같은 가정을 하고 프로그래밍하지 않았나요? 평상시에 저희가 작성하던 코드에 type-safe 조건을 만족시키기 위해 추가해야될 특정한 처리가 무엇인가 더 있는건지 궁금합니다...

**Comment by hyunminch** [comment]
(car '()) (cdr '()) 하면 올바르게 작동하지 않는다는 걸 중심으로 얘기하셨던거 같습니다

**Comment by kim-yoonseung** [comment]
결론부터 말하자면, 프로그래머의 실수를 사전에 막아주는 게 type-safe의 장점이라고 생각합니다. 어떤 프로그래머나 자신의 프로그램에 에러가 나서 중간에 멈추는 것을 원하진 않지만 언제나 그런 상황은 발생합니다. type-safe하게 짜면 훨씬 쉽게 이런 에러를 미연에 방지해줍니다.

예를 들면, 길게 정의한 함수 내용에 (list-ref n l) 과 같은 코드가 있을 때, 여기서 에러 발생이 가능한지는 실행을 해보지 않으면 확인하기가 매우 어렵습니다. 실행 중에 l의 길이가 바뀔 수 있고, n이 l의 길이보다 작아야 한다는 조건을 언제나 만족하는 지 알아야 하기 때문입니다.

매우 복잡한 코드 분석을 실행 전에 수행하더라도 100% 알아낼 수는 없습니다. 에러가 발생할 경우 지금까지 해왔던 실행이 모두 중단되므로, 만약 중요한 시스템을 돌리고 있었다면 서비스가 중단되어 큰 피해가 발생할 수도 있습니다.

하지만 type-safe한 경우는, 복잡한 코드 분석이 필요 없이, 실행 전에 타입만 체크하면 절대 실행 중 에러가 발생해서 실행이 멈추는 일은 없습니다. 위의 list-ref와 같은 경우, 오류 대신 unit을 리턴하게 되는데, 이 결과를 받아서 사용할 때는 언제나 case-sum을 사용하도록 사용자에게 제한이 있고, 이 경우 unit이 나오는 경우까지 반드시 고려를 하게 되므로 안전해집니다.

**Comment by seohongpark** [comment]
답변 감사합니다!
