### ISSUE TITLE
OCaml 4.02버전에 대해서..

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#106]
현재 OCaml 공식 페이지에 가면 윈도우 standalone 버전이 배포 중단되어있습니다.

hw6 안내문에 있는 페이지에 있는 링크
http://www.ocamlpro.com/pub/ocpwin/ocpwin-builds/ocpwin64/
에도 4.01밖에 없는것 같고요..

우분투에서는 4.02버전이 다운받아지긴 하지만 터미널환경에서만 코딩하게 되어있어 어떻게 이용해야할 지 잘 모르겠습니다..ㅠ 혹시 이것도 실습시간에 알려주시나요??

**Comment by kim-yoonseung** [comment]
그러면 4.01로 해도 좋습니다. 채점은 4.02로 하겠지만 만약 버전 문제때문에 점수에 문제가 생긴 경우는 4.01로 다시 채점하겠습니다. 아마 우리가 하게 될 숙제들에서는 문제가 발생하지 않을 것으로 생각합니다.

그리고 우분투에서는 보통 vim. emacs 등 일반적인 텍스트 에디터를 써서 코딩합니다. 실습시간에 튜토리얼을 진행할 예정인데, 특별한 것은 없고, 문법에 맞게 코딩한 후 숙제 설명대로 컴파일하는 과정을 거치면 됩니다.
