### ISSUE TITLE
6-7 무한루프

### ISSUE THREAD

**Issue by minkiminki** [snu-sf-class/PP2015f_TA#111]
6-7에 무한루프가 입력으로 들어올 수 있나요?
무한루프 여부를 확인할 수 있는 알고리즘이 존재하는 것 같은데 이것까지 구현하는 것이 숙제의 의도인지 궁금합니다.
예를 들어 (x := x)*U(x:=2)에 입력이 1이라면 {2}가 결과여야 하나요 구현하지 않아도 되나요?

**Comment by kim-yoonseung** [comment]
일반적으로 무한루프를 확인하는 알고리즘은 존재 안하지 않나요? halting problem과 관련있는 것 같은데요.

*는 임의의 횟수만큼 반복하는데, "임의의 횟수"는 무한대가 아니어서 언제나 언젠가는 끝납니다.
그리고 우리는 이 모든 가짓수를 다 실행해보지 않고도 가능한 모든 결과를 알아낼 수 있는데, 그 이유는 기계의 상태(변수가 가질 수 있는 값)이 유한하기 때문입니다.
