### ISSUE TITLE
6-3번과 6-7번에 대해서 질문입니다.

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#112]
먼저 6-3번에서는 corner case에 대한 처리가 궁금합니다.

(drop (LEAF Brazil) Brazil)
과 같이 결과값이 비어있게 되는 경우에 대한 처리는 어떻게 해야하나요?

6-7번에서는 -5와 +5 이외의 값을 변수가 "가지게 되면" 이 assign이 결과를 확인하라는 것 같은데요, 이 경우 assign되기 전 이 현재상태인가요 아니면 assign된 후가 현재상태인가요?? --> 문제에서 나와있는 예시에서 답을 찾았습니다. assign되기 전이군요!

**Comment by kim-yoonseung** [comment]
토너먼트에 자기밖에 없었는데 탈락해버리면 그냥 빈 스트링을 출력하면 됩니다.
다른 팀들도 있는데 탈락한 경우는 언제나 적절한 변환 방법이 있을 것 같습니다. 그 팀이 실격당한 것과 같은 효과를 내는 토너먼트가 존재할 것 같네요.

6-7은 assign되기 전입니다. -5 ~ +5 이외의 값은 기계가 가지는 것이 불가능한 값입니다.
