### ISSUE TITLE
ocaml 실행기에서 self-grade 돌려보는 법?

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#113]
안녕하세요! 조교님과 수강생 분들께 질문 드립니다.

혹시 ocaml 실행기에서 commonGrade 를 포함해서 실행기를 실행시키는 법을 알고 계시는 분 계신가요?

**Comment by eastskykang** [comment]
[이 문서](http://caml.inria.fr/pub/docs/manual-ocaml-4.00/manual023.html)에 따르면 ocaml top level (ocaml 실행기)에서 

``` ocaml
# #load "commonGrade.cmo";;
# #load "hw6_2.cmo";;
# #use "hw6_2_selfgrader.ml";;
```

이런 식으로 하면 실행기에서 체크 할 수 있는것 같긴 한데 컴파일 안하고 실행해볼 수는 없는건지 잘 모르겠네요.. 디버깅이 조금 불편해서 찾아보고 있는데 혹시 아시는 분 있으면 공유 부탁드릴게요!

**Comment by haekyu** [comment]
저는 그냥 ml코드 복붙해서 하는데............. 함수 수정할 때마다 다시 복붙해서 덮어씌우고요! 이걸 말씀하시는건지 잘 모르겠네요!
