### ISSUE TITLE
6-5번 문제의 식 최소화와 관련하여 

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#114]
안녕하세요 조교님 늘 수고 많으십니다!

6-5 번 문제에 보면 식의 최소화는 임의로 하라고 나와있는데, 어떤 식으로 채점이 될지요? 

이를테면, 

연산의 결과가 0 \* x 이런 식으로 나오는 항은 소거해야 할까요? 아니면 남겨두어도 채점기를 통과할 수 있을까요?

**Comment by kim-yoonseung** [comment]
네 남겨두어도 됩니다. 식의 변수에 숫자를 대입했을 때 같은 결과가 나오면 됩니다.

**Comment by kim-yoonseung** [comment]
이 문제는 그레이더를 조금 더 보완해서 올려드려야 할 것 같습니다.

**Comment by alxest** [comment]
조교님 천재...

**Comment by Clsan** [comment]
혹시 인풋으로 정리되지 않은 식 예를 들면 x \* 3 \* x와 같은 식도 들어올 수 있나요?

**Comment by kim-yoonseung** [comment]
네. 어떤 식이든지, 생성이 가능한 식은 입력으로 들어올 수 있습니다.
