### ISSUE TITLE
6-7 selfgrader 오류와 테스트케이스 하나 올립니다(..)

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#115]
먼저 selfgrader에 
5번째 줄
SEQUENCE (ASSIGN 1,  을
SEQUENCE (ASSIGN (NUM 1) 으로 고쳐야합니다.

그리고 13번째 줄
(exeval p1 -1) 을
(exeval p1 (-1)) 으로 고쳐야 합니다.

테스트케이스로 let p4 = (REPEAT (SEQUENCE ((CHOICE ((ASSIGN (ADD (VAR, NUM 1))), (ASSIGN (SUB (VAR, NUM 1))))), (ASSIGN (ADD (VAR, VAR))))));;
을 선언한 뒤 
exeval p4 0
exeval p4 1
exeval p4 (-1)
exeval p4 2
를 각각 입력해보면
[-2;0;2]
[0;1;2;4]
[-4;-2;-1;0]
[2]
가 나옵니다. 다른분들은 어떻게 나오시나요? 사실 테스트케이스라고 하기도 좀 민망하긴 한데..그래도 혹시나 해서 올려봅니다.

**Comment by KimHyeonwoo** [comment]
우선 좋은 테스트케이스 만들어주셔서 감사합니다.
그런데 저와 답이 조금 다른것 같네요.

[-2; 0; 2]
[-2; 0; 1; 2; 4]
[-4; -2; -1; 0; 2]
[2]

위처럼 나옵니다.

처음에 1을 대입했다고 생각합시다.
Loop 1) CHOICE 문에서 [0; 2] 가 되며 SEQUENCE 문에서 [0; 4] 가 됩니다.
Loop 2) CHOICE 문에서 [-1; 1; 3; 5] 가 되며 SEQUENCE 문에서 [-2; 2] 가 됩니다.
Loop 3) CHOICE 문에서 [-3; -1; 1; 3] 가 되며 SEQUENCE 문에서 [-2; 2] 가 됩니다.
Loop 4) 이후부터는 Loop 3과 같은 결과를 내므로 REPEAT 문의 결과는 [-2; 0; 1; 2; 4] 가 됩니다.

처음에 -1을 대입했다고 생각합시다.
Loop 1) CHOICE 문에서 [-2; 0] 가 되며 SEQUENCE 문에서 [-4; 0] 가 됩니다.
Loop 2) CHOICE 문에서 [-5; -3; -1; 1] 가 되며 SEQUENCE 문에서 [-2; 2] 가 됩니다.
Loop 3) CHOICE 문에서 [-3; -1; 1; 3] 가 되며 SEQUENCE 문에서 [-2; 2] 가 됩니다.
Loop 4) 이후부터는 Loop 3과 같은 결과를 내므로 REPEAT 문의 결과는 [-4; -2; -1; 0; 2] 가 됩니다.

**Comment by eastskykang** [comment]
저도 Kim Hyeonwoo 님과 동일하게 나오는 것 같습니다! 좋은 정보 감사합니다!

**Comment by eodmsabc** [comment]
저는 답이 다르게 나오네요

초기상태 0으로 시작하는 경우 repeat을 한 번 실행했을 때 상태가 [-2; 0; 2] 로 변하고
그 다음 [-3; -2; -1; 0; 1; 2; 3] 으로 변합니다
이 때, -1과 1은 sequential 문에 따라 계속 실행되어 다시 -2와 2가 되지만
-3과 3은 -6과 6으로 상태가 변하면서 그 상태로 프로그램이 종료된다고 생각합니다.

그래서 저는
exeval p4 0  => [-3; -2; 0; 2; 3]
exeval p4 1  => [-3; -2; 0; 1; 2; 3; 4; 5]
exeval p4 (-1)  => [-5; -4; -3; -2; -1; 0; 2; 3]
exeval p4 2  => [2; 3]

이 나옵니다

**Comment by KimHyeonwoo** [comment]
위의 제 댓글이 틀렸네요 ㅠㅠ

https://github.com/snu-sf-class/PP2015f_TA/issues/118 글에서 저는 빈 리스트가 나왔는데 지금은 수정했습니다.

수정한 결과는 바로 위의 eodmsabc 님의 결과와 동일합니다.

저와 결과가 같게 나오셨다던 EastskyKang 님도 한 번 체크해보시는게 좋을것같네요!!

**Comment by Heejaejoo** [comment]
의문이 있는데, REPEAT은 가능한 결과상태가 모두 나올때까지 돌아가야 하잖아요. 
exeval p4 0 ->  [-3; -2; 0; 2; 3] 이라면, SEQUENCE문을 한번 더돌리면 -3은 -4에서 멈출꺼같고 3은 4에서 멈출거 같은데 그럼 결과에 -4, 4 가 포함되어  [-4; -3; -2; 0; 2; 3 ;4] 가 나오고, 최종적으로는  [-5; -4; -3; -2; 0; 2; 3 ;4;5] 가 나와야 맞지 않을까요?

**Comment by kyungissac** [comment]
#129 를 보면 범위를 벗어나면 기계가 모든 괄호를 빠져나와 프로그램이 종료된다고 가정했기에 [-3; -2; 0; 2; 3] 이 답인 것 같습니다.

**Comment by eastskykang** [comment]
@eodmsabc @kyungissac @KimHyeonwoo 안녕하세요. 답변달아주셔서 감사합니다. 동작 방식에 의문이 있습니다. 만약에 여러개의 state 를가지고 있는 상태에서 halt 가 되면 모든 명령이 all stop 되는 건가요? 

이를테면 (x:= x + x)\* 이 [-3 -1 0 1 3] 상태에서 동작하게 된다면 어떻게 되어야 할까요? -3, 3 의 경우에는 halt 라서 동작이 멈추는데 -1, 0, 1 의 경우에는 계속 동작을 하게 됩니다...

**Comment by kyungissac** [comment]
최종 결과에는 -3, 3을 두고 나머지는 계속 동작 시켜서 추가적인 결과들을 얻게 되면 그것들도 최종결과에 추가하시면 됩니다.

**Comment by wortgg** [comment]
-3에서 -4 또는 -2가 되고, 그 다음 cmd가 실행되면 -8, -4가 되므로 -8일때는 종료되고 -4일 때는 REPEAT이 진행되는 거 아닐까요? 마찬가지로 -4에서 -5, -3이 되고 그 다음 cmd에서 -10, -6이 되므로 종료되니까 현재상태는 -5 또는 -3에서 종료된다고 보면 -5 -4 -3 -2 0 2 3 4 5 가 되는게 아닐까요?

**Comment by taehwoi** [comment]
@wortgg님 저는 다음과 같은 과정을 통해 [-2,0,2]가 된다고 생각하였습니다.
REP 0: [0]
REP 1: [0]-> (SEQ: [-1,1] -> ASS: [-2,2])
REP 2: [-2,2]-> (SEQ:[-3,-1,1,3] -> ASS: [-3,-2,2,3] ) 

싹쓸이 실행기는 REP 2의 마지막 상태인 -3,-2,2,3 에 대해서 각각 미라지 언어를 실행한 결과물을 모은다고 볼 때, -3, 3은 범위 밖으로 나가 미라지언어가 종료했으므로 REP횟수와 상관없이 종료하게 되고, -2,2에 대해서 REP을 실행하는 것은 REP2와 동일하므로 REP0, REP1, REP2의 가능한 결과들을 합친 [-3,-2,0,2,3]이 맞다고 생각합니다.

**Comment by wortgg** [comment]
@indiofish 님 -3의 상태에서 -2 또는 -4의 상태를 가지고, 그 상태에서 -4 또는 -8의 값을 가질 수 있는데, -4는 포함되지 않을까요? 즉 -3 -> CHOICE에서 -3+1을 선택, 현재 상태 -2 -> -2 + -2 = -4 로 -4를 상태로 가질 수 있을 것 같습니다.

**Comment by wortgg** [comment]
리스트 전체로 보면 -3이 포함되어 있을 경우 halt지만 상태가 -3에서 시작한다는 관점에서 보면 -4 상태로 이행될 거 같은데... 제가 잘못 생각한 점이 있나요?

**Comment by taehwoi** [comment]
@wortgg님 음 저는 REP2에서 SEQ에서 ASS로 넘어갈 때 -3,3은 각각 6,-6이 되기 때문에 입력이 -3,3인 미라지 프로그램은 -3,3으로 종료되버리기 때문에 다음 REP때 종료된 프로그램은 고려하지 않는다고 (-3,3으로는 SEQ단계에 들어가지 않는다고) 생각하였는데 듣고보니 그 말씀에도 일리가 있는 것 같네요...
@kim-yoonseung 조교님께서 판단해주시면 감사하겠습니다.

**Comment by wortgg** [comment]
아 생각해보니 -3이면 끝나서 REP이 실행이 안되네요 생각이 짧았습니다 ㅋㅋ..

## 

제가 위와 같이 생각한 이유는, -3으로 halt가 된다는 것을 생각하지 않고

-3의 상대로 REPEAT이 돌아간다고 생각했기 때문입니다.

즉 기계 상태가 범위를 초과한 순간 REPEAT은 안돌아 가는데, 저는 돌아간다고 생각한 거죠..

**Comment by iKoru** [comment]
저도 @indiofish 님이 말씀하신것처럼 나오네요!

**Comment by kim-yoonseung** [comment]
제 생각에도 [-3,-2,0,2,3]인 것 같네요. 제 코드도 이렇게 나옵니다. 이유는 @indiofish 님의 설명대로입니다.
