### ISSUE TITLE
6-7의 동작과 관련하여 질문입니다.

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#117]
다음의 seq를 최초상태 1에서 수행했을때 올바른 결과가 어떤 것인지 궁금합니다.

```
((x eq 1? x:=x+1) U (x neq 1? x:=x-1))*; (x eq 1? x:=x+1)
```

첫 cmd를 실행한 결과 가능한 상태의 리스트는 [1, 2] 이와 같은데, 그럼 두번째 cmd 까지 시행한 결과는 [2]가 되는 것인지요?

**Comment by kim-yoonseung** [comment]
네, 최종 종료 시에 1로 끝나는 경우가 없다면 1은 빼야 합니다.
