### ISSUE TITLE
6-7 현재상태로 종료

### ISSUE THREAD

**Issue by eodmsabc** [snu-sf-class/PP2015f_TA#118]
x := 3; x := x + x
를 초기 상태 2에서 실행하면 sequential 문을 시행하면서
x에 3이 어사인되고 이어서 x에 6이 어사인되면서
invalid한 state를 가지게 되어 프로그램이 중단되고 결과 상태 리스트가 [3]이 되는지

아니면 sequential 문 자체가 실행이 안되어서 결과 상태 리스트를 초기 상태인 [2]라고 봐야 하는지
아니면 정상 종료가 아니기때문에 빈 리스트가 나오는지 궁금합니다.

**Comment by kim-yoonseung** [comment]
실제 기계의 동작과 같다고 생각하시면 될 것 같습니다.
이 sequence의 경우, 첫 번째 문장이 잘 실행되었으면 상태가 3으로 바뀌었고, 그 상태에서 다음 문장을 실행하려다 이상하게 되어 종료하므로 3을 가진 상태에서 끝납니다.
