### ISSUE TITLE
다른 파일에 정의된 함수를 이용해도 되나요?

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#12]
예를 들어 제 hw1-2에서 정의한 함수(crazy2add 이외의 따로 정의한 함수들)를 hw1-3에서 이용해도 되는 건지 궁금합니다.

**Comment by kim-yoonseung** [comment]
본인이 새로 정의한 함수의 경우에는 ctrl c,v를 이용해서 붙여넣으시면 됩니다.
