### ISSUE TITLE
6-1 질문입니다.

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#121]
1. (memo-ways 100 100)이 5초정도 걸리는데 이 정도면 적당한 memoization이라고 볼 수 있는 건가요? 본 과제의 시간제한을 알고 싶습니다.
2. 반드시 교재 3.3.3장과 연습문제 3.27과 같은 memoization을 수행해야 하는 건가요? 아니면 개념적으로 memoization을 수행했으면 어떤 방법이든 인정이 되는건가요...?

**Comment by kim-yoonseung** [comment]
1. 그 정도면 좋습니다. 10초의 시간을 주어 실행할 것이고, 크기는 대략 50x50 까지 할 것입니다.
2. 개념적으로 memoization을 하시면 됩니다.
