### ISSUE TITLE
6-1 memoize 에 대한 질문

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#126]
lst 라는, 지금까지의 계산 결과들을 저장하고 있는 객체를 하나 선언해서 전역변수(?)로 쓰고 있습니다. 

이렇게 되면 전역변수로 선언했기 때문에 위에서 실행한 결과들이 계속 기억되게 됩니다. 
이를테면 

``` racket
(memo-ways 100 100)
(memo-ways 10 10)
```

이렇게 하면 100 100 을 계산한 결과들이 10 10 을 계산할때 다시 쓰이게 됩니다. 이런식의 구현도 허용이 될까요? 혹은 memo-ways를 할 때마다 저장한 결과들을 초기화 해줘야 할까요?

**Comment by kim-yoonseung** [comment]
그렇게 하셔도 좋습니다.
