### ISSUE TITLE
6-3 selfgrader 질문

### ISSUE THREAD

**Issue by kyungissac** [snu-sf-class/PP2015f_TA#127]
6-3 selfgrader에서

(NODE (NODE (NODE (LEAF Korea, LEAF France), LEAF Brazil), LEAF England)) 

가장 바깥쪽 NODE 안에 NODE만 1개 있으므로 아래 tourna의 정의에 어긋나지 않나요?

type tourna = LEAF of team
                   | NODE of tourna \* tourna

이러면 selfgrader의 drop에 tourna가 아닌 것이 들어가게 되는 것 같습니다.

**Comment by KimHyeonwoo** [comment]
저도 처음에 갸우뚱했었는데 

NODE (NODE (LEAF Korea, LEAF France), LEAF Brazil) 와 

LEAF England가 각각 tourna이면서 NODE로 묶여있는거니까 괜찮은 것 같아요. 

제일 바깥쪽의 괄호를 하나씩 지우시면 이해가 편할 것 같네요!! 

그리고 애초에 그게 tourna가 아니었다면 결과가 나오는게 아니라 type error가 나옵니다.

**Comment by kyungissac** [comment]
감사합니다
