### ISSUE TITLE
6-5 6-7 질문입니다.

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#129]
[6-5]

출력하는 ae에 TIMES []이나 SUM []과 같은 항이 있어도 되나요?

즉, TIMES []는 1로, SUM []는 0으로 간주되는 것인지와 이를 자유롭게 처리/출력에 이용해도 상관없는지를 알고 싶습니다.

또한 POWER (x, -1)이나 POWER (x, 0)이나 POWER (x, 1)과 같은 항이 있어도 되는지 알고 싶습니다.

---

[6-7]

-5~5가 아닌 값이 들어왔을 때 '현재상태로 실행 끝'이라는 것은 더이상 아무 연산도 실행하지 않고 중첩된 모든 괄호들(?)을 다 빠져나와 그 현재 상태가 출력값이 되는, 마치 exception과 같은 상황의 처리를 하라는 것인가요?

**Comment by kim-yoonseung** [comment]
6-5는 오늘 안으로 실제 채점과 같은 원리의 자가채점기를 다시 올려드리도록 하겠습니다.

그 채점기에 의하면 하시려는 대로 하실 수 있을 겁니다.

또한 power가 가지는 정수는 음수 또는 0이 될 수도 있습니다.

6-7에서는 말씀하신 대로입니다. 기계가 실행하다가 꺼져버린다고 생각하시면 될 것 같습니다.
