### ISSUE TITLE
Challenge의 환경에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#143]
myeval 함수의 인풋은 symbol형태로 되어있는데요,

그렇다면 들어오는 symbol의 parsing을 하는 방법이 있나요?? symbol은 그 자체로 그냥 symbol이라고만 배워서 symbol에 대해서 뭔가를 할 수 있는 방법이 있는지 모르겠습니다.

또 myeval function은 racket에서 만들면 되는건가요?

**Comment by kim-yoonseung** [comment]
정확히 말하면 인풋은 symbol이 아니라 list거나 숫자 등입니다. 
'abcd 는 심볼이지만 이런 인풋은 우리의 문법에는 없습니다.
'(car a) 와 같은 인풋은 '(1 2 3) 처럼 리스트로 인식되고, (car '(car a)) 를 하면 'car 라는 심볼이 나옵니다.

또한 '3, '#t 등은 자동으로 3, #t 로 인식되며, 심볼로 인식되지 않습니다.

myeval은 Racket에서 만들면 됩니다.
