### ISSUE TITLE
Challenge if문 질문입니다.

### ISSUE THREAD

**Issue by eodmsabc** [snu-sf-class/PP2015f_TA#146]
구현해야하는 if문이 racket과 동일하게 작동해야하는지,

아니면 if문의 첫 번째 인자 계산값이 boolean이 아닐 때
type error를 띄워야 하는지 궁금합니다.

**Comment by kim-yoonseung** [comment]
첫 인자가 boolean이 아닌 경우에 Racket과 똑같이 하셔도 되는데, 특별히 이 경우에는 boolean이 아니면 type error 띄워도 되는 걸로 합시다.
