### ISSUE TITLE
8-2 질문입니다.

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#165]
StringSetQQ에서 StringSetQ가 같다는 것은 무슨 뜻인가요?
이것이 physical equality를 뜻하는지 structural equality를 뜻하는지 아니면 queue2list의 값이 같은 것을 뜻하는지 궁금합니다.
([a, b], [c])와 ([a], [c, b])는 같은 StringSetQ인가요?

**Comment by kim-yoonseung** [comment]
queue를 밖에서 보기에 동작이 똑같으면 같은 것입니다.
같은 순서로 원소를 넣고 뺐을 때 같은 결과가 나오면 됩니다.
그러니까 내부 구조와는 관련이 없습니다.
밑의 예는 아마 똑같이 동작할테니 같다고 취급하면 됩니다.
