### ISSUE TITLE
HW8-1 에서 OCaml 모듈 신택스 관련한 질문 + 테스트 질문입니다.

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#176]
숙제 메뉴얼에서 

``` ocaml
module StringQ: Queue with type element = string
      = struct ... end
```

이런 식으로 모듈을 선언하라고 되어 있습니다. 한가지 궁금한게 있는데 `with type element = ?` 의 역할이 무엇인가요? 저렇게 선언을 해줘도 

``` ocaml
module StringQ : Queue with type element = string = 
struct 
    type element = string 
    ....
end       
```

이런식으로 type element 를 재차 선언하지 않으면 컴파일 에러가 나더라구요. 

더불어서 StringQ와 StringQQ 모듈은 대부분 선언이 거의 비슷할 것 같습니다. 여기서 함수 구현을 반복하고 싶지 않을때, 일종의 클래스 상속의 개념이 Ocaml에도 있는지 궁금합니다.

---

추가로 hw8-1의 테스트는 올바른 입력만 들어온다고 가정해도 괜찮을까요?

**Comment by kim-yoonseung** [comment]
예를 들어 `StringQ` 모듈에서 `...with type...`의 역할은 `StringQ`의 모듈 타입, 즉 sig가 "element = string인 `Queue`" 라는 것을 외부로 드러내줍니다.
그냥 `Queue`만 붙이면 외부에서 사용할 때 element의 타입을 볼 수가 없습니다. 따라서 `StringQ.enq` 를 이용해 큐에 원소를 넣을 때 "abc"등의 string을 넣으려고 하면 "abc"의 타입은 string이지, StringQ.element(=Queue.element)가 아니라며 거절합니다.
하지만 sig에 추가로 element = string이라고 선언해주면 위와 같이 쓸 수 있습니다.
이러한 방법은 sig에 추가해준 것이므로 module의 정의 (struct) 내부에는 다시 element의 정의를 써주어야 합니다.

또한 큐들의 비슷한 부분을 매번 코딩하지 않고 모듈을 자동으로 생성해주는 문제가 8-3입니다. C나 Java의 클래스와 일치하는 개념은 아니지만 비슷한 점도 있으므로 숙제를 풀어보시면서 이해하실 수 있을 것입니다.

8-1에서 올바르지 않은 입력이 무엇인지 잘 모르겠습니다. 일단 모든 테스트가 타입에 맞게 들어오긴 합니다.
