### ISSUE TITLE
1.2번 과제와 1.3번 과제에 대한 문의 

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#18]
안녕하세요. 

구현 방식에 따라서 **1.2번**과 **1.3번**의 답은 다를 수 있을 것 같습니다. 
이를테면 계산의 결과가 1이라고 했을 때 똑같은 1이라도 여러가지 표현으로 쓰여질 수 있을것 같습니다. 
`+` (= 1)
도 가능하지만 
`-+` (= 2 - 1 = 1)  도 1입니다. 

그렇다면 1.2번 과제와 1.3번 과제를 채점할 때에는 함수의 결과값을 정수로 변환한 것을 정답과 비교하여 답이 옳은지 평가하는 것인지 궁금합니다.

**Comment by ky1emoon** [comment]
밑에 q&a 중 crazy2val을 이용해 채점한다는 말이 있었는데... 그러면 상관 없지 않을까요?

**Comment by eastskykang** [comment]
아 그렇다면 무방해질 것 같네요! 감사합니다.

issue는 closed 했다가 혹시 몰라서 reopen 해놓습니다!

**Comment by kim-yoonseung** [comment]
네, 채점은 `crazy2val`을 이용합니다.
