### ISSUE TITLE
프로젝트 질문

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#180]
OCaml에서 뼈대코드에 let으로 정의된 함수를 let rec으로 바꿔도 되나요?

**Comment by seohongpark** [comment]
덤으로 syntax.ml 뼈대코드 중 exp_to_string에서 = 대신 -을 출력하는 오타가 있는것 같습니다.

**Comment by kim-yoonseung** [comment]
ocaml에서 let -> let rec으로 바꾸는 것은 자유롭게 하시면 됩니다.

또한 syntax.ml에 오타를 방금 수정하였습니다. (tar 파일에는 아직 못 수정했습니다.) 알려주셔서 감사합니다. 혹시 지금까지 프로젝트를 많이 진행하신 분들은, 실행 및 채점에는 관계가 없으니 걱정하지 않으셔도 됩니다.
