### ISSUE TITLE
hw8-4 관련 질문

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#181]
안녕하세요! 조교님 늘 수고가 많으십니다. 

8-4번 문제에 질문이 있습니다. 

rotate 함수의 경우에는 box를 인자로 받게 되어 있습니다. 궁금한 것은 rotate 라는 것이, 주어진 모듈의 박스를 시계방향으로 회전시키는 함수인 것 같은데 왜 굳이 함수의 형태로 선언되어야 하는 것인지 잘 모르겠습니다.

예를 들면

``` ocaml
module B4 = Glue (A) (A') (B) (B')
let _ = output (fun () -> B4.box = 
    GLUED (BOX (NW, TURTLE), BOX (NE, TURTLE), BOX (NW, WAVE), BOX (NE, WAVE)))
let _ = output (fun () -> B4.rotate B4.box = 
    GLUED (BOX (SE, WAVE), BOX (NE, TURTLE), BOX (SE, TURTLE), BOX (NE, WAVE)))
```

여기에 보면 B4.rotate는 B4.box를 재차 인자로 받게 되어있습니다. 굳이 이렇게 인자를 받을 필요가 있는건지요?  B4.rotate는 그냥 B4.box를 회전한 값을 출력하도록 변수로 선언을 해도 괜찮을 것 같은데 말이죠.

혹은 B4.rotate 에 다른 모듈의 box가 인자로 들어와도 제대로 처리가 되도록 구현을 해야하는 것인지 궁금합니다. 

즉

``` ocaml
B4.rotate A4.box
```

혹은 block 자리에 직접 입력을 아래와 같은 방식으로 해주는 

``` ocaml
B4.rotate  BOX (NW, TURTLE))
```

와 같은 입력도 들어온다고 생각을 해야 하는 걸까요?

뭔가 위의 두 예의 경우에는 속구현 감추기 / 모듈화의 목적에 부합하지 않는 것 같은데, 왜 이런 입력이 들어올 소지가 있도록 과제 스펙이 주어진 것인지 이해가 잘 되지 않습니다. 혹시 제가 놓치고 있는 부분이 있는걸까요?

감사합니다!

**Comment by kim-yoonseung** [comment]
말씀하신 것들이 일리가 있고, 제가 과제를 만들었다면 이런 식으로 만들진 않았을 것입니다만, 이런 식으로 만든 이유는 module 안에 입,출력이 있는 함수를 넣고싶었던 것 같습니다.

이 문제에서는 모듈 안에 box가 하나만 있어야 하기 때문에 이상한 구현이 되었는데, box가 여러 개 있다면 이런 식으로 구현하겠지요.

전에도 이와 관련된 질문이 있었는데, B4.rotate B4.box 와 같이 자신의 박스를 회전하는 경우만 테스트합니다.

**Comment by eastskykang** [comment]
@kim-yoonseung 조교님! 빠른 답변 감사합니다! 한가지만 더 여쭤보겠습니다. pp 함수 같은 경우에는 이번 과제에서는 구현이 의무인 것은 아닌건가요??

더불어서 말씀하신대로 구현을 하는 경우에는, 그럼 Glue 모듈의 rotate에는 GLUED type 의 box만 인자로 들어오고 BOX type 의 box가 인자로 들어오면 exception을 발생시켜도 괜찮을까요?

**Comment by kim-yoonseung** [comment]
우선 pp의 경우는 아예 안 하셔도 되고, 다른 종류의 box의 경우 exception을 내도 됩니다.

**Comment by alxest** [comment]
고수키무킹무성
