### ISSUE TITLE
(프로젝트)eq의 파라미터 종류는 int로 한정되나요?

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#182]
중복이면 죄송합니다.. 어디선가 본것같은데 못찾겠어서 다시 질문드립니다.

eq의 파라미터는 int뿐인가요? 아니면 const? 아니면 모든 타입에 대해서도 처리해야 하나요?

**Comment by kim-yoonseung** [comment]
네 int만 합니다. 다른 타입에 대해서 구현하는 것은 자유입니다.
