### ISSUE TITLE
(프로젝트)letrec의 구현방식에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#184]
테스트케이스 중에서 
(letrec ((x 1) (y (+ x 1))) (letrec ((x y) (y (+ x 2))) y))
와 같은 항목이 있는데요,

racket에서 돌려보면 두번째 letrec에서의 y가 초기화 이전에 사용되었기 때문에 오류를 뱉습니다.

그런데 분명히 y는 앞쪽 letrec에서 정의한 것 아닌가요?
letrec에서 바인딩하는 이름은 그 이름이 정의될 때의 환경을 그대로 가지고 가기때문에 앞서 y를 x+1, 즉 2로 바인딩 해두었으니 x에는 2가 들어가야 하는것 아닌가요?

제가 어느부분을 잘못 생각하고 있는지 설명해주시면 감사하겠습니다 ㅠ.ㅠ

**Comment by kim-yoonseung** [comment]
이게 letrec의 동작 방식 때문인데, 두 번째 letrec을 처리할 때 x와 y가 바인딩 될 것을 보고 둘을 uninitialize로 만든 후 x와 y의 값을 계산합니다. 이 때 이전의 y 값은 지워지는 것이죠.
강의 슬라이드에 이 과정이 자세히 나와있으니, 읽어보시면 확실하게 알게 되실 것 같습니다.

**Comment by iKoru** [comment]
감사합니다. 그런데 구현이 왜 이렇게 되는지를 알 수 있을까요? 처음에 초기회를 하는 귀찮은 과정을 굳이 거치지 않더라도 기존에 있는 환경을 사용하면 오류가 날 프로그램도 오류가 안나도록 프로그램을 짤 수 있을텐데요. 이렇게 초기화 과정을 거침으로 인해서 얻는 장점이 있나요?

**Comment by kim-yoonseung** [comment]
letrec에서 x와 y의 값을 정의할 때, x를 정의할 때 쓰이는 y는 앞으로 정의할 y인 건 아셨죠? 이 y는 이전의 y의 값을 초기화하는 게 아닙니다. 이전에 y가 있든 없든 새로운 y를 environment에 추가해서 그 값을 undefined로 하는 것입니다.
이렇게 하지 않으면, `(let ([y 1]) (letrec ([y 3]) 4) y)` 같은 식을 실행할 때 결과가 3이 나와버리겠죠.
두 개가 메모리 상의 다른 값을 가리키는 서로 다른 environment이니까 다른 값을 가지는 게 자연스럽습니다.
초기화를 이전 y 값을 찾아서 그 값으로 하는 방법도 있겠지만, 언어의 semantics만 헷갈리게 하고 그닥 좋은 점이 없을 것 같습니다.

**Comment by YeongjinOh** [comment]
조교님, 제시하신 예시는 (저희 프로젝트에서 주어진) let이란 expression의 정의에서 벗어나는 형식이 아닌가요?
 E부분에 (letrec ([y 3]) 4) 과 y 이렇게 2개의 expression이 들어갈 수 있나요??
이 부분과 관련하여 질문이 하나 더 있습니다.
(eval '(let ((x (lambda x x))) (x 3))) 의 결과값이 '(3)으로 출력되더군요. 그런데 여기서 (lambda x x) 라는 expression은 저희 프로젝트에서 주어진 형식에서 벗어나는 것이 아닌가요? 그러면 위와같은 인풋을 받았을때 myeval함수는 에러를 출력해야하나요?

**Comment by kim-yoonseung** [comment]
저 예시 자체는 문법에 벗어나서 그대로 못 쓰지만 저 식과 동등하면서 우리 문법에 맞는 방법이 있습니다. 다만 그렇게 쓰면 식을 읽기 복잡합니다. 여기 써보자면 letrec 부터의 부분을 `(let ([tmp (letrec ...)]) y)`와 같이 쓰면 됩니다.

또한 람다 식에서는 언제나 변수들이 괄호 안에 있을 때만 고려하면 됩니다. 그렇지 않으면 예외처리를 해주면 됩니다.
