### ISSUE TITLE
프로젝트 질문

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#185]
프로젝트에서 함수 스택은 최대 어느 정도까지 테스트해볼 예정이신가요?

프로젝트 문서에 999999짜리 예제가 있어서 이정도는 들어올 것 같은데, 혹시 함수 호출 횟수의 상한을 스펙화해주실 수 없을까 해서 질문을 올려 봅니다.

이를 알 수 있다면 environment의 최대 개수를 미리 설정할 수 있어 편할 것 같습니다.
## 

Handler에서도 if와 마찬가지로 not-boolean 값들을 결과로 냈을 때 exception을 일으켜도 되나요?
아니면 라켓처럼 false가 아닌 값들은 모두 true로 처리해(도/야) 되나요?
## 

void형을 사용할 때, 라켓에서는 (set-mcar! x 3) (set-mcdr! x 5) (+ 1 2)과 같이 이어서 쓸 수 있는데 혹시 이러한 형식까지 myeval이 지원을 해야하나요? 아니면 let에서 단순히 필요없는 임시 변수(ocaml로 따지자면 let _의 _와 같은 느낌)에 void형을 저장한다는 방식만 지원해도 되는 건가요?
## 

문제 7번의 채점 기준은 어떻게 되나요? 실행 시간이 기준이 되는건지, 아니면 스펙에 나와 있는 대로 얼마나 많은 종류의 function에 메모이제이션이 적용되는지를 평가하는 건가요? 만약 후자라면 어떤 방식으로 평가되는 건지 궁금합니다.

**Comment by kim-yoonseung** [comment]
1. 스택의 개수를 정할 필요는 없다고 생각됩니다. 우선 컴퓨터마다 메모리 크기가 다르기도 하지만, 999999의 경우는 tail recursion이 되도록 설계하면 스택이 아예 안 쌓이기 때문입니다.
2. if의 경우는 boolean만 처리할 수 있으면 됩니다. 다른 타입의 경우 예외를 내셔도 됩니다. Racket처럼 다른 타입의 경우 모두 #t를 내도 괜찮습니다.
3. myeval은 문서에 나온 문법의 프로그램만 잘 처리할 수 있으면 됩니다. 따라서 언급하신 문법은 다루지 않아도 되고, 임시 변수에 넣는 형식의 방법으로 똑같은 일을 하는 테스트를 하시면 됩니다.
4. 많은 종류의 function에 memoization을 적용할 경우 실행시간이 빨라지므로 같은 이야기라고 생각합니다만, 전자라고 할 수 있습니다. 채점 기준은 한 테스트 당 시간 내에 계산이 끝나면 O, 아니면 X입니다. memoization 기술을 쓸 경우 확실히 빨리 끝나는 계산만 할 예정이므로 시간 기준은 크게 걱정하지 않으셔도 됩니다. 물론 실행 결과는 memoization을 안 썼을 때와 완전히 같게 나와야 합니다.
