### ISSUE TITLE
(프로젝트)exception handling의 로직(semantics)가 궁금합니다.

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#186]
구현해야 하는 예외처리의 로직이 궁금합니다. 

구글링을 해봐도 어려운 설명밖에 없고 강의자료에도 정확히 나와있지 않은 것 같아서 질문으로 드립니다.

예외처리를 하는 정확한 논리과정이 설명된 곳이 있을까요???

**Comment by kim-yoonseung** [comment]
(with-handlers ([a b] [c d] ..) body) 를 만나면 body를 실행합니다.
실행 중에 (raise E)를 만나면 앞으로 남은 실행을 모두 취소하고, handler의 앞에서부터 체크하여 (a E) = true 이면 (b E)를 실행하고, (c E)= true 이면 (d E)를 실행하는 식으로 다음 진행을 합니다.

만약 raise를 만나서 실행을 모두 취소할 때, with-handlers가 끝까지 없으면 ocaml에서  UNCAUGHT_EXCEPTION을 raise하면 됩니다.

**Comment by taehwoi** [comment]
라켓에서는 (with-handlers ([a b] [c d] ..) body)에서 (a E)의 값이 boolean이 아닌 다른 값이어도 (b E)를 실행하던데 저희의 구현에서는 (a E)는 boolean만이라고 가정하고 풀어도 괜찮을 지 궁금합니다.

**Comment by kim-yoonseung** [comment]
racket에서는 boolean이 아닌 다른 값이 boolean 값으로 사용될 때는 모두 #t로 실행되는 걸로 보입니다.

우리는 boolean일 때만 나온다고 가정하고 풀어도 좋습니다.

**Comment by indiofish** [comment]
아하 감사합니다.

**Comment by taehwoi** [comment]
그리고 with-handlers가 예외처리를 할 때,  (a E)가 #t일 때 (b E)를 실행하는 과정에서의 환경은 이전까지의 실행이 담긴 환경인지 아니면 handlers내부의 새로운 환경인지 궁금합니다.

**Comment by kim-yoonseung** [comment]
실험을 해보면 (with-handlers ... 을 만날 때의 환경을 사용할 겁니다.
b가 lambda 일 텐데, evaluate가 with-handler를 처리할 당시에 진행될 겁니다.
즉,

```
(let ((a 3))
  (with-handlers (((lambda (x) #t) (lambda (x) a))) (let ((a 5)) (raise 1))))
```

의 결과는 3입니다.

**Comment by kyungissac** [comment]
예외처리에 있어서 그냥 필요할 때마다 (raise "error occured : (reason)") 하고, with-handlers같은 것을 사용하지 않아도 되나요?
아니면 반드시 with-handlers를 써서 uncaught exception이 없도록 해야 하나요?

추가질문 : selfgrader에 1번~20번까지 test를 적당히 입력하되, 중간에 10번쯤에 예외처리가 발생하는 test가 있으면 중간에 끊어지는 건가요? 아니면 11~20번은 정상 실행하는 모습을 보여야 하나요?

**Comment by kim-yoonseung** [comment]
제가 질문을 잘 이해했는지 모르겠습니다만, raise 해서 with-handlers가 받아줄 수 있으면 받아주고, 받아주는 with-handlers가 없다면 uncaught_exception을 내놓으면 됩니다.

또한 실제 채점시에는 당연히 테스트 케이스 사이에 연관관계 없이 따로 채점됩니다.

**Comment by iKoru** [comment]
@LastOne817 님께서 올려주신 테스트케이스 중에서

(with-handlers (((lambda (x) (= x 3)) (lambda (x) (\* x 3)))) (with-handlers (((lambda (x) (raise (+ x 2))) (lambda (x) (\* x 3)))) (raise 1)))

와 같은 것이 있는데요, 이 문장을 실행할 때

1) (lambda (x) (= x 3)) (lambda (x) (\* x 3)의 핸들러를 등록한 뒤 (with-handlers (((lambda (x) (raise (+ x 2))) (lambda (x) (\* x 3)))) (raise 1))문장을 실행

2) (lambda (x) (raise (+ x 2))) (lambda (x) (\* x 3))핸들러를 등록한 뒤 (raise 1)을 실행

2-1) 1을 raise

2-2) 가장먼저 (lambda (x) (raise (+ x 2))) (lambda (x) (\* x 3))핸들러의 선조건이 1과 일치하는지를 검사

2-2-1) (+ x 2)를 x가 1인 환경에서 raise -> handler를 등록한 시점의 환경과 핸들러를 이용하여 예외처리

2-2-2) (lambda (x) (= x 3)) (lambda (x) (\* x 3)의 핸들러의 선조건을 검사. 그런데 raise된 것이 (+ x 2)인데, handler를 등록한 시점에서 x는 존재하지 않음 --> unbound error

지금 이렇게 된 상황에서 막혀있는데요, 이것에 대해서 해결할 수 있는 방법을 생각해 본 결과 : 

(1) raise 할 때 (+ x 2)를 하는 것이 아니라 그 때의 환경에 맞는 값을 raise; 즉, 3을 raise
--> 이 때의 문제점은 (+ x 2)를 계산한 결과는 value_t인데, value_t타입을 raise할 수는 없음. 또 letrec으로 정의된 함수가 raise되고 이를 받는 쪽에서 application만 할 경우 또 마찬가지로 환경에 없는 상황 발생.

(2) (+ x 2)와 함께 해당 시점의 환경을 함께 넘겨줌
--> 이 때의 문제점은 핸들러 선언 당시의 환경과 겹칠 경우. 예를 들어 핸들러 선언 당시에 x = 2로 선언되어 있었을 경우 의도한 결과에서 벗어난다.

(3) (+ x 2)를 단순히 x = 1 로 replace해줌
--> 이 때의 문제점은 letrec으로 정의되어 있는 재귀함수를 raise할 경우 무한루프에 빠지게 됨 / 혹은 결론적으로 핸들러의 환경을 건드릴 수 밖에 없음

와 같은 문제에 봉착해있습니다. 이런 경우는 어떻게 처리하면 좋을까요??ㅠㅠ @kim-yoonseung 조교님 도움을 요청합니다ㅠㅠㅠ

**Comment by jooyany** [comment]
저 테스트케이스에 대해 저도 다른 질문이 있습니다!
(with-handlers (((lambda (x) (= x 3)) (lambda (x) (\* x 3)))) (with-handlers (((lambda (x) (raise (+ x 2))) (lambda (x) (\* x 3)))) (raise 1)))
이 경우는 
(lambda (x) (raise (+ x 2))) 가 boolean type이 아니어서 우리 문제에서는 고려하지 않아도 되는 것인가요??

**Comment by kim-yoonseung** [comment]
@iKoru raise는 value_t 타입을 받아야 하는데 왜 그것이 불가능한가요? 또한 letrec으로 정의된 함수를 raise하는 것도 문제가 없어야 할 것 같은데요.

@jooyany 우리 문제에서는 true/false는 확실히 boolean인 경우만 다루기로 했으므로 저 부분은 예외처리를 하셔도 좋습니다.
