### ISSUE TITLE
value_t에 값을 추가해도 되나요?

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#189]
value_t에 EXCEPTION 타입 등을 추가해도 되나요?

또 value_to_string의 여러 출력들을 마음대로 손대도 되는지도 궁금합니다.

**Comment by kim-yoonseung** [comment]
그렇게 사용하고 싶으실 경우 value_t2 처럼 자신만의 타입을 만들고, 최후에 value_t로 변환해주세요.
이렇게 하시면 테스트용으로 value_t2 를 string으로 바꾸는 출력 함수를 만드셔서 사용하시면 될 것 같습니다. value_to_string은 수정하지 않았으면 합니다.
