### ISSUE TITLE
crazy2*.rkt 입력 관련 질문드립니다.

### ISSUE THREAD

**Issue by taehwoi** [snu-sf-class/PP2015f_TA#20]
안녕하세요. 

과제의 pdf 파일에는 이친수 +-를 '(p . n) 와 같은 pair로 정의해서, 
문제를 해결하는 과정에서 cdr를 할 때, pair?임을 확인해야 합니다. ((cdr (cdr '(p . n))은 오류를 출력해서요)

그런데, 자가채점기에서는 두 개 짜리 이친수를 '(p n)와 같은 리스트로 정의해서 pair?임을 확인하지 않고 계속 cdr하다가 null?인지만 확인해줘도 됩니다.

구현하기에는 후자가 훨씬 편한데, 채점시에는 어떤 입력이 들어오는 지 궁금합니다.
감사합니다.

**Comment by indiofish** [comment]
몰랐는데 자가채점기에는 하나짜리 입력도 'z가 아니라 '(z)와 같은 방식으로 되어있네요. 후자로 구현해도 괜찮은 것인가요?

**Comment by taehwoi** [comment]
작년 학기 과제 pdf로 crazymul을 풀었었는데 이번 학기에는 pdf 내용도 바뀐걸 몰랐네요.. 닫도록 하겠습니다.
