### ISSUE TITLE
(프로젝트) letrec 문법

### ISSUE THREAD

**Issue by minkiminki** [snu-sf-class/PP2015f_TA#202]
(letrec ((f (lambda (x) g))(a (f 1))(g (lambda (x) 1))) 1)
(letrec ((f (lambda (x) g))(a 1)(g (lambda (x) 1))) 1)
(letrec ((f (lambda (x) g))(a f)(g (lambda (x) 1))) 1)

하면 할수록 racket에서 letrec이 어떻게 구현되어 있는건지 모르겠습니다. 위의 세 경우 중 첫번째 것만 error가 나고 나머지 두개는 잘 돌아갑니다. lambda 안의 것은 바인딩 되었는지 확인을 안 하나 싶지만 첫번째에서 에러가 나는 것을 보면 뭔가 다른 방식인 것 같은데 말이죠...

그리고 다른 게시물에서 각 이름들을 uninitialize 하는 방식으로 한다고 하셨는데 이 내용이 자세히 나온 것이 강의자료 어느 부분인지 알 수 있을까요?

**Comment by wortgg** [comment]
첫번째 거는 g가 아직 바인딩 되어 있지 않은 상태에서 사용하셔서 그렇습니다
나머지는 프로시져로 바인딩 되기 때문에 아직 사용하지 않았으므로 에러가 나지 않구요

**Comment by minkiminki** [comment]
아 컴파일 오류인줄 알고 질문을 했는데 컴파일 오류가 아니라 실행 오류군요...

**Comment by kim-yoonseung** [comment]
강의자료 1번에서 본 거 같은데, 아니더라도 네다섯 개밖에 없으니까 직접 찾아보시면 금방 찾을 것 같습니다.
