### ISSUE TITLE
lambda의 인자가 여러개 들어오는 경우와 관련하여

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#214]
조교님 안녕하세요! 

프로젝트 스펙에 보면 lambda의 인자에 *표시가 되어 있는데 이런 경우 인자를 여러개 받을 수 있다는 의미인 것으로 알고 있습니다. 

람다에 인자가 여러개 들어올 수 있도록 구현을 해야하는지요??? 
감사합니다!

**Comment by kim-yoonseung** [comment]
네, 람다는 인자를 많이 받을 수 있습니다.

또한 추가하자면, +는 길이가 1 이상임을 의미하는데, ocaml 코드를 보면 아시겠지만, 문제를 간단하게 하기 위해 그냥 *와 같게 정의하였습니다.

**Comment by eastskykang** [comment]
@kim-yoonseung 조교님 답변 감사드립니다! 한가지만 더 여쭤보겠습니다. `let`이나 `letrec` 의 경우에는 let\* 처럼 윗줄에서 선언된 것들을 사용할 수 있도록 구현해야 하는지 궁금합니다. 이를테면 

``` racket
(let ([x 1] [y x]) y)
```

가 제대로 동작할 수 있어야 하는것인지요?

**Comment by taehwoi** [comment]
``` racket
(let ([x 1] [y x]) y)
(letrec ([x 1] [y x]) y)
```

let의 경우에는 이전까지의 환경으로 내부의 변수들을 실행해서 환경에 추가하니까 y 입장에서 x가 뭔지 모르지만 letrec은 현재의 환경을 전체환경에 추가한 뒤에 실행하기 때문에 y가 x를 볼 수 있을 것 같습니다. 일단 racket에서는 위에는 에러 밑에는 정상 실행 되네요.

**Comment by eastskykang** [comment]
@indiofish 님 답변 감사합니다! racket에선 let에서는 인식할 수 없고 let\* 에서는 정상 동작하는 걸로 알고 있습니다. 한줄마다 environment를 update 하느냐 그렇지 않느냐의 차이라서 구현이 크게 어려울 것 같지는 않습니다만, 문제에서 요구하는 것이 어떤 건지 궁금하네요

**Comment by taehwoi** [comment]
음 저는 일단 라켓과 동일할 수록 좋을 것 같아서 그렇게 했습니다..ㅋㅋ

**Comment by kim-yoonseung** [comment]
let과 let*은 의미가 다르므로 let의 의미를 따라야 합니다.
