### ISSUE TITLE
프로젝트 6번의 semantic 관련 질문입니다.

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#220]
밑에 분이 올려주신 테케의 6-12를 보면,

(with-handlers ((a b)) c) 라는 구문이 있을 때 라켓은 a, b를 value(즉 람다 함수)가 될 때까지 eager evaluation을 한 뒤 c를 진행하다 raise가 발생하면 핸들링을 진행한다는 것을 알 수 있었는데요,

조교님은 #186 에서

"(with-handlers ([a b] [c d] ..) body) 를 만나면 body를 실행합니다.
실행 중에 (raise E)를 만나면 앞으로 남은 실행을 모두 취소하고, handler의 앞에서부터 체크하여 (a E) = true 이면 (b E)를 실행하고, (c E)= true 이면 (d E)를 실행하는 식으로 다음 진행을 합니다."

라고 하셨는데, 이는 a, b의 계산을 body에서 raise가 될 때까지 미루는 lazy evaluation의 방법으로 보입니다.

일반적인 경우에는 두 방법이 큰 차이가 없겠지만, 테스트케이스 6-12와 같이 a가 (set-mcar! ...) (lambda (x) ...)과 같이 side-effect가 있는 식이라면 두 방법 간 결과 차이가 생기게 됩니다.

그렇다면 핸들러의 처리는 어떤 방식을 택하는 것이 맞는 건가요? lazy하게 처리해야 하는지, eager하게 처리해야하는지, 혹은 이러한 테스트케이스는 고려하지 않아도 되는건지 조교님의 답변을 듣고 싶습니다.
## 

덤으로, 라켓의 인터프리터 실행 속도는 어느 정도까지 고려해야 되는건가요?

라켓에서는 오캐믈과 달리 제가 시간복잡도를 크게 신경쓰지 않고 구현하여서 (끝재귀를 지원함에도)
(letrec ((f (lambda (x n) (if (= x 0) n (f (- x 1) (+ n x)))) )) (f 999999 0) )과 같은 테스트케이스가
시간 내에 나오지 않습니다.

제 구현에서는 라켓으로 구현한 인터프리터의 시간복잡도가 생긴 environment 개수의 제곱에 비례하는 것 같은데, 이정도면 1번 문제를 통과할 수 있는 것인지 아닌지를 알 수 있게끔, 입력으로 들어오는 식의 계산량과 시간에 대한 개략적인 기준이 있으면 좋을 것 같습니다!

**Comment by garion89** [comment]
(with-handlers
    ( ((lambda (x) (= x 3)) (lambda (x) (\* x 3))) ((raise 1111)(raise 2222)) )
  (with-handlers
      ( ((lambda (x) (raise (+ x 2))) (lambda (x) (\* x 3))) )
    (raise 1)
    )
  )

제가 이러한 케이스를 만들어봤는데 여기서 raise 1111이 먼저 실행되어 uncaught exception이 발생합니다. body 부분을 먼저 계산한다고 하면 raise 1이 제일 먼저 evaluation되어 handling부분으로 넘어가 raise (+ x 2) 부분의 x로 1이 들어가 raise 3을 실행시킨후 그 후에 다시 (= x 3)을 evaluation하여 true를 발생시켜 (\* x 3)을 실행시켜야되는데 말이죠.

이런걸 보아 eager evaluation하는 걸로 보입니다.

**Comment by kim-yoonseung** [comment]
제가 #186 에서 말한 것은 사실 eager하게 a와 b를 계산하는 것을 의도했는데 말이 빠져서 저렇게 보이게 되었네요. (with-handlers ([a b]) c) 를 만나면 [미리 a와 b를 계산한 다음], c를 계산하다 raise e가 일어나면 (a e)를 그 때 계산한다는 의도였습니다. 그런데 지금 읽어보니 저 부분이 빠지면 전혀 다르게 읽히는군요.

그리고 별개로, 이전에 교수님께 이에 대해서 채점을 어떻게 할 지를 여쭈어본 적이 있는데, exception의 evaluation 순서는 그냥 어떻게 해도 괜찮게 해라..는 답을 받아서, 저런 케이스는 각자 자유롭게 처리해도 틀리지 않게 하겠습니다.

또한 실행 시간은 넉넉하게 드릴 것이나, 다른 학생의 답과 유의미하게 차이나게 느리다면 효율적인 구현이 아니므로 감점될 수 있습니다.
