### ISSUE TITLE
(끌올)exception handling의 semantics

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#224]
@LastOne817 님께서 올려주신 테스트케이스 중에서

(with-handlers (((lambda (x) (= x 3)) (lambda (x) (\* x 3)))) (with-handlers (((lambda (x) (raise (+ x 2))) (lambda (x) (\* x 3)))) (raise 1)))

와 같은 것이 있는데요, 이 문장을 실행할 때

1) (lambda (x) (= x 3)) (lambda (x) (\* x 3)의 핸들러를 등록한 뒤 (with-handlers (((lambda (x) (raise (+ x 2))) (lambda (x) (\* x 3)))) (raise 1))문장을 실행

2) (lambda (x) (raise (+ x 2))) (lambda (x) (\* x 3))핸들러를 등록한 뒤 (raise 1)을 실행

2-1) 1을 raise

2-2) 가장먼저 (lambda (x) (raise (+ x 2))) (lambda (x) (\* x 3))핸들러의 선조건이 1과 일치하는지를 검사

2-2-1) (+ x 2)를 x가 1인 환경에서 raise -> handler를 등록한 시점의 환경과 핸들러를 이용하여 예외처리

2-2-2) (lambda (x) (= x 3)) (lambda (x) (\* x 3)의 핸들러의 선조건을 검사. 그런데 raise된 것이 (+ x 2)인데, handler를 등록한 시점에서 x는 존재하지 않음 --> unbound error

지금 이렇게 된 상황에서 막혀있는데요, 이것에 대해서 해결할 수 있는 방법을 생각해 본 결과 : 

(1) raise 할 때 (+ x 2)를 하는 것이 아니라 그 때의 환경에 맞는 값을 raise; 즉, 3을 raise
 --> 이 때의 문제점은 (+ x 2)를 계산한 결과는 value_t인데, value_t타입을 raise할 수는 없음. 또 letrec으로 정의된 함수가 raise되고 이를 받는 쪽에서 application만 할 경우 또 마찬가지로 환경에 없는 상황 발생.

(2) (+ x 2)와 함께 해당 시점의 환경을 함께 넘겨줌
 --> 이 때의 문제점은 핸들러 선언 당시의 환경과 겹칠 경우. 예를 들어 핸들러 선언 당시에 x = 2로 선언되어 있었을 경우 의도한 결과에서 벗어난다.

(3) (+ x 2)를 단순히 x = 1 로 replace해줌
 --> 이 때의 문제점은 letrec으로 정의되어 있는 재귀함수를 raise할 경우 무한루프에 빠지게 됨 / 혹은 결론적으로 핸들러의 환경을 건드릴 수 밖에 없음

와 같은 문제에 봉착해있습니다. 이런 경우는 어떻게 처리하면 좋을까요??ㅠㅠ

**Comment by iKoru** [comment]
이와 덧붙여서 한가지만 더 질문을 드리고 싶습니다.

with-handlers에 선언되는 핸들러 함수들은 선언될 때 한번 씩 선언이 되어야 하는 부분인가요? 
(let ((a (mcons 1 2))) (with-handlers (( (let ((temp (set-mcar! a 7))) (lambda (x) #t)) (lambda (x) x)) ( (lambda (x y) #t) (lambda (x) x))) (mcar a)))
와 같은 경우 핸들러 중간에 변경을 해주는 부분이 있는데 이를 먼저 수행한 뒤에 본 문장을 수행해야하는지 궁금합니다.

**Comment by kim-yoonseung** [comment]
원래의 글에 방금 답변을 썼는데, (1)에서 값을 raise하는 게 맞는 방법있ㄴ데 왜 안되는지를 설명해주실 수 있나요?

또한 보통 실행 중에 핸들러를 만나면 얘들을 실행해주고 본문을 실행하지만, 교수님이 exception의 실행 순서에 크게 신경쓰게 하지 말라고 하셔서, 핸들러와 바디의 계산 순서는 어떻게 하셔도 좋습니다.
