### ISSUE TITLE
(let ((a 1) (a 2)) a)의 입력과 관련하여

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#225]
채점을 할때 이런 입력이 가능할까요? 

racket의 경우에는 error를 출력하는데, 따로 exception 처리를 해줘야 하는지, 아니면 이런 입력이 들어오지 않는다고 생각해도 될지 궁금합니다.

**Comment by kim-yoonseung** [comment]
이 경우는 runtime이든 parsing 중이든 에러를 내는 게 맞습니다.
