### ISSUE TITLE
if문의 참거짓 판별

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#226]
예전 이슈에서 본 것 같은데, 한 번 더 확인하려고 찾으니 못찾겠어서 질문드립니다.

racket에서는 if 1 () () 와 같이 if 바로 뒤에 #f가 아니면 그냥 참이라고 해석한다고 하는데요,

마찬가지로 with-handlers에서도 인 것 같습니다.

이때에도 true로 계산되는 값만 처리하면 되나요?

**Comment by kim-yoonseung** [comment]
저도 이 질문을 보았던 것 같습니다. 일단 우리는 if 뒤에는 boolean value만 잘 처리할 수 있으면 되고, 그렇지 않을 경우에는 참으로 처리하셔도 되고 런타임 에러를 내셔도 됩니다. handler도 마찬가지입니다.
