### ISSUE TITLE
1.2과 1.3번에서 null 인풋이 들어오는 예외사항에 대한 질문 

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#23]
안녕하세요. 

1.2번과 1.3번에서 두 숫자중 하나가 null로 들어오는 상황이 존재할 수 있는지, 그리고 그 경우에 어떤 처리를 해야하는지 스펙을 알려주시면 감사하겠습니다!

**Comment by kim-yoonseung** [comment]
null은 귀납적으로 정의된 2친수 정의에 없기 때문에 들어오지 않습니다.

모든 분들을 위한 추가 정보: 특별한 지시가 없다면 예외처리의 경우는 임의로 하시면 되는데 (즉 안 해도 됨), 다만 예외인 경우와 예외가 아닌 경우를 확실히 구분하셔야 합니다. 예를 들면 리스트가 들어올 경우 빈 리스트, 즉 null이 들어올 경우를 잊으면 안 되겠죠.
