### ISSUE TITLE
제출 파일 이름 질문

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#233]
instruction에 보니까 첫번째 파일을 challenge.rkt파일을 제출하라고 하셨는데 제가 받아서 낸 파일은 chal.rkt입니다. 혹시 이름을 바꿔서 다시 제출해야하나요??

**Comment by kim-yoonseung** [comment]
파일 이름은 사실 한글만 안 들어있으면 전혀 문제 없습니다. 어차피 제가 채점 시에 다 이름을 새로 바꾸기 때문입니다.
한글이 있는 경우는 파일 전송 시에 문제가 있어 제가 이름을 직접 바꿔줘야 하긴 하지만 감점되지는 않습니다.
