### ISSUE TITLE
1-4의 struct를 이용한 구현에서의 equal? 문제 

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#29]
저는 leaf와 node를 각각 `struct`로 구현하였습니다. 

문제가 하나 있는데 struct로 구현을 하게 되면 
`(equal? (leaf 1) (leaf1))`을 해보면 `#f`가 나오게 됩니다. 

아마도 struct란 것이 클래스의 개념과 유사한 것이라서 서로 다른 객체로 인식을 하게 되는것 같은데요. 

이 문제의 [해결책](http://docs.racket-lang.org/guide/define-struct.html)을 찾긴 했습니다만 이런 구현이 딱히 문제가 될 소지가 있는건 아닌지 염려됩니다. (해당 solution 은 struct의 equal을 비교하는 경우에는 struct들의 attribute(?)들을 서로 들여다보고 비교하게 하는 방식입니다. 약간의 편법? 을 사용하는 것 같네요.)

**Comment by kim-yoonseung** [comment]
이런 경우는 `equal?`로 비교가 가능해야 한다는 조건이 없기 때문에 감점이 되지 않고, 만약 감점되더라도 말씀해주시면 확인 후 점수를 드립니다.
사실 `struct` 같은 feature는 이 과목에서는 나오지 않아 고려하지 않았었고, 실습 시간에 했었던 list, pair 등으로 충분히 모든 강의 내용이 커버될 것입니다.
