### ISSUE TITLE
require 관련 질문드립니다.

### ISSUE THREAD

**Issue by taehwoi** [snu-sf-class/PP2015f_TA#33]
과제에 명시적으로 1-4를 사용하라고 되어 있는 hw5~7을 제외하고, 다른 과제에도 `require`를 사용해도 괜찮은지 궁금하여 질문드립니다. 
(hw1-2, hw1-3등에 hw1에서 정의한 함수(`crazy2add` 외에도) 사용하고자 하는 목적입니다.)

또한, `require`가 있는 과제에서`require`하는 코드가 틀렸을 경우에는 채점이 어떻게 진행되는지도 궁금합니다.

감사합니다.

**Comment by kim-yoonseung** [comment]
require는 이번 숙제에서는 추가하지 마세요.

본인이 새로 정의한 함수를 또 쓰고 싶을 경우는 코드를 복사해서 붙여넣으시면 됩니다.

HW1에서는 require하는 코드는 각자의 코드가 아니라 저희가 구현한 코드를 사용합니다.
