### ISSUE TITLE
과제 2-3 iter 관련 질문 드립니다.

### ISSUE THREAD

**Issue by eodmsabc** [snu-sf-class/PP2015f_TA#34]
iter 함수의 인자 n 에 음수가 들어올 수 있나요?

만약 들어온다면 어떻게 처리해야 하는지 궁금합니다.

**Comment by kim-yoonseung** [comment]
문제를 자세히 보시면 |n|이라고 써 있을 것입니다.

| | 는 아시다시피 절대값 기호입니다.
