### ISSUE TITLE
2-3 실행 관련 오류

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#39]
![screenshot from 2015-10-12 00 49 12](https://cloud.githubusercontent.com/assets/7664952/10417567/2e2f3a7c-707b-11e5-935c-a41ec19d6d0b.png)

스크린샷인데요, ㅠㅠ 왼쪽이 selfgrader 실행화면이고 오른쪽이 2-3 화면입니다.

왼쪽을 보면 selfgrader는 에러를 뱉는 것을 확인할 수 있는데요, 아예 (equal? ~)있는 부분에서 ill-formed code 에러가 발생합니다. 
반면 오른쪽에서(hw2-3.rkt 파일) 테스트케이스의 내부를 실행시킨 결과는 selfgrader의 비교 대상과 같다는 것을 확인할 수 있습니다. 

이 현상이 윈도우에서 일어나서, 우분투로 옮겨서 테스트를 해봤지만 마찬가지입니다.

이런 경우 어떻게 해야하나요? ㅠㅠ

**Comment by iKoru** [comment]
아 참고로 저 스크린샷 화면이 우분투에서 실행한 화면이고, 윈도우에서도 저 ill-formed code에러가 같은 곳에서 발생합니다.

**Comment by kim-yoonseung** [comment]
혹시 저에게 메일로 코드를 보내주신 분인가요?

**Comment by iKoru** [comment]
아니요, 다른 분 말씀하시는 것 같습니다

**Comment by kim-yoonseung** [comment]
그러면, 메일로 2-3 숙제 파일을 보내주실 수 있으신가요? 저희도 테스트를 좀 해봐야 알 것 같습니다.

**Comment by iKoru** [comment]
메일로 보내드렸습니다!

**Comment by eastskykang** [comment]
저도 비슷한 문제가 있습니다.  ill-formed code 에러가 뜨네요! 

마찬가지로 런하고 커맨드 창에서 직접 넣어주면 특별한 에러가 안뜨고 전부 결과가 잘 나옵니다.

**Comment by iKoru** [comment]
이것이 설마 교수님이 수업시간에 말하신 racket 오류체크를 통과했음에도 불구하고 일어나는 런타임오류..? 성적 1단계 상승...?ㅋㅋ(장난)

**Comment by eastskykang** [comment]
저.. 저도 껴주세요

**Comment by kim-yoonseung** [comment]
결과는 메일로 보내드렸지만, 제 windows 환경과 martini에서는 문제가 없었습니다.

Racket을 삭제 후 재설치 하시거나, 문제가 있을 경우 martini에서 테스트해보시거나 하는 것을 추천드리고 싶네요.

**Comment by eastskykang** [comment]
저는 지금 martini에서 돌려봤는데 에러없이 동작하는 것 같습니다. 이전에 조교님께서 달아주신 답변을 보니까 windows 환경에서 drracket에서 발생하는 에러인거 같습니다. 

[이 issue 내용](https://github.com/snu-sf-class/PP2015f_TA/issues/21)을 참고하시면 좋을 것 같습니다!

다소 빈번히 발생하는 문제인것 같네요!

**Comment by iKoru** [comment]
@EastskyKang 님 감사합니다.ㅎㅎ
