### ISSUE TITLE
hw2 selfgrader을 이용하는 데에 문제가 있습니다.

### ISSUE THREAD

**Issue by SoheeLee** [snu-sf-class/PP2015f_TA#41]
![help](https://cloud.githubusercontent.com/assets/11474724/10519549/2a07de26-73a1-11e5-85ed-8eeecf3ff130.PNG)

다음과 같은 에러가 일어나는데 어떻게 해결해야 할까요?
hw2-1과는 상관없이 일어나는 것 같습니다.

**Comment by esifea** [comment]
안녕하세요, 프로그래밍 원리 TA입니다.

에러 메시지만 봐서는 `common-grade.rkt` 파일쪽에 뭔가 문제가 있는 듯 한데, 제가 확인한 것으로는 
`common-grade.rkt`파일에서 `#lang-racket`을 제거했을 때 같은 오류가 발생했습니다.

혹시 `common-grade.rkt` 파일을 확인해주실 수 있으신가요?

**Comment by sangmoon** [comment]
hw2 file을 github에서 raw 파일로 받으면 commom-grade.rkt 파일이 이상해지는 것 같습니다.
저도 위와 같은 증상을 겪었는데 github 에 있는 common-grade.rkt 소스를 복사해서
다운 받은 common-grade.rkt파일로 붙여넣기 하시면 해결될 것 같습니다.

**Comment by kim-yoonseung** [comment]
hw2에서, tar 파일 안에 있는 common-grade.rkt 파일이 잘못되어 수정하였습니다.

아마 그걸 받으신 것 같은데, 다시 받으시거나 hw1에서 쓰신 common-grade.rkt로 바꿔주시면 됩니다.

불편을 드려 죄송합니다.

**Comment by SoheeLee** [comment]
말씀하신 대로 잘 해결했습니다! 답변 감사합니다.
