### ISSUE TITLE
숙제 3-1 의 뼈대코드 관련한 질문

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#45]
- sigma

``` racket
(define (sigma lower upper)
  (lambda (f)
    (define (loop n)
      (if (> n upper) 0
          1
          (+ (f n) (loop (+ n 1)))))
    (loop lower)
    )
  )
```

위의 코드를 보면 

``` racket
(if (> n upper) 0
          1
          (+ (f n) (loop (+ n 1))))
```

이 부분의 syntax에 문제가 있는 것을 확인할 수 있습니다. 어차피 실행하지 않을 부분이기 때문에 무시하고 진행해도 괜찮을지, 아니면 단순 오타인지 궁금합니다.

---
- map

``` racket
 (define (map f l)
  (if (null? l) () 
      (cons (f (car l)) (map f (cdr l)))
      )
  )
```

여기에 보면 () 라는 정체불명(?)의 괄호쌍 명령이 있습니다. 이 부분은 어떻게 해석해야 할지 궁금합니다.

**Comment by dj-shin** [comment]
- sigma에서의 `1`은 과제 pdf에서 복붙해오시면서 딸려온 페이지 넘버 같네요. `1`을 지우면 잘 될것 같습니다.
- map에서 `()`는 `'()`인것 같습니다.

**Comment by eastskykang** [comment]
@LastOne817  안녕하세요! 말씀하신 내용이 맞는것 같습니다. 근데 제가 가져온 뼈대코드가 git clone 으로 가져온 뼈대 코드인데 오타가 들어가 있는 것이 조교님께서 의도하신 것인지, 아니면 실수로 들어가 있는 건인지 궁금하네요!

**Comment by kim-yoonseung** [comment]
1은 제가 뼈대코드를 만들면서 복사하다 딸려온 부분이 맞습니다.
()는 교수님이 pdf를 만드실 때 '를 빠뜨린 것 같습니다.
둘 모두 수정하였습니다.
알려주셔서 감사합니다.
