### ISSUE TITLE
숙제 3-2, can-enter의 타입 관련 질문드립니다.

### ISSUE THREAD

**Issue by taehwoi** [snu-sf-class/PP2015f_TA#46]
안녕하세요.
자가채점기에는 미로가 다음과 같이 정의되어 있고,
`can-enter`는 그 번호에 해당하는 maze리스트의 한 원소(이자 리스트)를 반환하도록 되어있습니다.

``` racket
(define maze1
  (cons 4
        '((1 4) (0 5) (3 6) (2 7)
          (0 5 8) (1 4) (2) (3)
          (4 12) (10 13) (9 11 14) (10)
          (8 13) (9 12) (10 15) (14))))
(define (can-enter maze room) 
  (list-ref (cdr maze) room)) 

(define room1 0)
```

그래서 `(can-enter maze1 room1)` 을 하게되면 `'(1 4)`를 반환하게 됩니다.
그런데 문제는 다음에 1번과 4번방에 대해서 (can-enter maze1 1), (can-enter maze1 4)를 할 일반적인 방법이 없는 것 같습니다.

물론 문제에서는 can-enter가 list기 때문에, `car` `cdr`를 통해 각각의 원소에 접근할 수 있지만, maze의 구현이 아래처럼 정수가 콤마로 구분된 문자열로 바뀐다면

``` racket
(define new-maze
  (cons 2
        '("1,2" "0"
          "0,3" "2"
          )))
```

(can-enter new-maze 0)는 `"1,2"`를 반환하기 때문에, `car` `cdr`로는 접근할 수 없습니다.

그래서, `can-enter`가 hw3-2-library의 구현과는 무관하게 라켓의 리스트 자료구조형을 반환한다는 보장이 있거나, hw3-2-library 내부에서 정의된 집합에 따라서  라켓의 `car` `cdr`의 역할을 하는 무언가가 필요할 것 같습니다. 
만약 미로의 구현이 위의 new-maze처럼 바뀐다면, can-enter는 `"1,2"`를 콤마를 기준으로 쪼개서 '(1 2)를 반환한다고 생각하고 풀어도 괜찮을지 궁금합니다.
감사합니다.

**Comment by kim-yoonseung** [comment]
숙제 document를 보시면 `can-enter`의 타입은 `room × maze → room list`로 되어있는데요,
`room list`의 `list`는 우리가 알고 있는 Racket의 `list`가 맞습니다.
따라서 `car`, `cdr`을 사용해도 됩니다.
따로 설명이 있는 게 좋았겠군요.

덧붙이면, 아시다시피 `room set`의 `set`은 우리가 알 수 없는 자료형입니다. 따라서 car, cdr 등을 사용할 수가 없겠죠.
