### ISSUE TITLE
hw 3-3관련 질문입니다. (.ps 실행파일)

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#49]
maze-pp를 이용하면 .ps 파일이 만들어지기는 하는데요, 이것을 실행시킬 프로그램이 적당하지 않은 것 같습니다.
먼저 제시된 http://www.ghostscript.com/download/gsdnld.html 의 파일은 OS에서 위험 파일이라는 이유로 차단하고 있습니다. 두번째로 제시된 것은 다운받아서 실행하면 ghostscript가 존재하지 않아서 실행이 불가능하다고 하고요. 
또한 racket에서 랜덤성을 보장한다는 것은, 같은 인풋에 대해서도 매번 다른 결과를 내야 한다는 의미인가요? 그렇다면 racket에서 랜덤하게 값을 리턴해주는 함수가 무엇인지 궁금합니다. 그리고 문제에서 제시된 미로의 정의: 입구와 출구가 맨 윗줄과 맨 아랫줄 각각 하나씩 있고, 통로가 한가지 경우만 존재한다는 것을 어떻게 보장할 수 있나요?

**Comment by kim-yoonseung** [comment]
어떤 OS를 쓰시는지는 모르겠으나 ps파일이 특이한 포맷은 아니므로 viewer가 있을 것입니다. 꼭 코드에 제시된 viewer로 보실 필요는 없습니다. GSviewer는 아마 ghostscript를 설치해야 쓸 수 있을 겁니다.
아니면 온라인에서 ps를 pdf로 바꿔주는 곳도 있네요. 구글에 검색해보니 (https://online2pdf.com/convert-ps-to-pdf) 또는 (https://www.ps2pdf.com/convert.htm) 같은 곳을 찾았는데, 안전한 곳인지는 잘 모르겠습니다.
3-3의 채점 기준은 교수님과 다시 얘기해본 후 확실히 하여 공지해드리겠습니다.

**Comment by iKoru** [comment]
덧붙여 미로를 만들 때 3-2 라이브러리에서 사용한 함수들을 사용할 수 있을지 궁금합니다.

**Comment by kim-yoonseung** [comment]
3-3 숙제를 할 때는 뼈대코드에 포함된 모든 파일에서 코드를 복사해서 사용하실 수 있습니다.
3-2 또는 3-3 라이브러리 함수를 복사해서 사용하시면 숙제하기 수월할 것입니다.

require는 하지 마시고 꼭 코드를 복사해서 사용하세요.

**Comment by iKoru** [comment]
3-2와 3-3에서의 차이점이 있는 것 같습니다. 3-2에서는 room 자체가 encapsulation되어있지만 3-3에서는 room을 지칭할 수 있는 방법이 해당 room의 위치(int*int)입니다. 그렇다면 이 두 가지를 어떻게 연관지을 수 있는 방법이 있나요?

**Comment by kim-yoonseung** [comment]
네, 3-2와 3-3은 미로 모양도 다르지만 library의 구현도 다른 방식으로 되어있죠.
그래서 그대로 쓸 수는 없고, 각자가 코드를 이해해서 적당히 수정해야 하겠습니다.
3-2를 쓰는 게 가장 간단한 방법은 아닐 수도 있습니다.
