### ISSUE TITLE
과제 3-3 채점기준

### ISSUE THREAD

**Issue by eodmsabc** [snu-sf-class/PP2015f_TA#52]
과제 3-3 채점기준에서 헛걸음질을 포함한 걸음의 총 수가 복잡도의 기준이 된다고 하셨는데
이 경우 랜덤생성없이도 복잡도만을 최대화하는 (같은 입력 n, m에 대해 매번 같고, 미로 해답도 매우 간단한)미로를 만들 수 있습니다.

실제로 selfgrader채점 결과 복잡도만을 최대화하는 미로가 랜덤 생성 미로보다 복잡도 점수가 높게 측정되었습니다. 여기에 대한 명확한 기준이 필요할 것 같습니다.

**Comment by kim-yoonseung** [comment]
무작위성은 채점 기준이 아닙니다. 문서를 읽어보시면 랜덤하게 생성해야 한다는 조건은 없습니다.
