### ISSUE TITLE
과제 3-3 질문

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#53]
채점 기준에서 5번 미로를 생성하여 각각 확인한다고 하셨는데, 만약 무작위적으로 미로를 만든게 아니라면 (n m이 같을 시) 5개의 동일한 미로가 생기게 될 것 같습니다.

이 경우는 (그 한 미로의 점수) \* 5가 제 점수가 되는 것인가요?

**Comment by kim-yoonseung** [comment]
n과 m은 당연히 다르게 테스트 할 것입니다.
