### ISSUE TITLE
과제 3-3 selfgrader 질문입니다

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#54]
이 파일의 실행 결과는 어떻게 읽어야 하냐요??

evaluate가 총 5번 실행되는데 
처음 두 가지는 과제로 나온 genMaze를 사용하지 않는 것으로 봐서 그냥 selfgrader 자체를 테스트하는 목적인 것 같은데 맞나요? 
맞다면 actual testing이라고 나온 부분만 보면 되는건가요? 그렇다면 뒤에 나온 숫자는 무슨 의미인가요? 
제 생각에 이것이 말씀하신 "복잡도"인 것 같은데, 미로의 크기에 따라 어느정도의 값이 나오면 통과라고 할 수 있을까요? 

아래는 실행 결과입니다. 확인을 부탁드립니다!

testing a maze which doesn't have a path from start to end (0 pts):
'(fail . 0)
testing a maze which have multiple paths (1 pts):
'(not-unique . 0)
actual testing:
'(unique . 12)
'(unique . 67)
'(unique . 412)

이렇게 나오는 게 맞는건가요??

**Comment by kim-yoonseung** [comment]
위의 두 테스트는 그레이더 자체를 테스트하는 것이고 아래 세 개가 mazeGen을 테스트하는 것입니다.

결과 pair의 앞부분이 'fail 이면 경로가 없는 것, 'not-unique면 경로가 있지만 복수의 개수인 것입니다.

'unique는 경로가 유일한 경우이며, 이 때 복잡도를 계산해서 보여줍니다.

결과가 언제나 'unique로 나오면 맞게 한 것이고, 복잡도는 높을 수록 좋으며 전체 학생들 중에서 상대적으로 많이 나올 경우 점수를 더 받을 수 있습니다.
