### ISSUE TITLE
Delay 제출 점수

### ISSUE THREAD

**Issue by eodmsabc** [snu-sf-class/PP2015f_TA#56]
과제를 원래 기한에 제출하고 제출 기한이 지난 뒤 한번 더 Delay 제출하게 되면
나중에 제출된 코드로 채점하고 Delay가 적용된 점수로 들어가는지
아니면 두 점수 중 높은 점수로 인정되는지 궁금합니다.

**Comment by kim-yoonseung** [comment]
높은 점수로 합니다.
