### ISSUE TITLE
3-3 채점기 미로탐색 알고리즘

### ISSUE THREAD

**Issue by eodmsabc** [snu-sf-class/PP2015f_TA#59]
실제 채점에 사용되는 3-3 grader프로그램 내부에 구현되어있는 solver가
미로의 답을 찾는 순간 탐색을 중지하고 그동안의 걸음 수를 복잡도로 나타내는지, 아니면
답을 찾더라도 아직 방문하지 않은 길을 모두 탐색한 후에 미로 자체의 복잡도를 나타내는지 궁금합니다.

만약 전자의 경우라면, solver가 한번에 미로를 풀어버렸을때 실제로 아무리 복잡한 미로라도 확률에 따라 낮은 복잡도를 가질 수 있는 것 같아서 질문드립니다.

**Comment by kim-yoonseung** [comment]
모든 길을 탐색합니다.
