### ISSUE TITLE
3-3 의 미로 생성 알고리즘. 기존 알고리즘 사용에 관하여

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#61]
이미 유효한 미로 생성 알고리즘으로 알려져 있는 알고리즘 들이 많이 있는데 그 중에 하나를 가지고 구현해도 괜찮을까요?

**Comment by kim-yoonseung** [comment]
네. 인터넷에서 알고리즘을 찾아보아도 좋습니다.
