### ISSUE TITLE
3-3 라이브러리 함수 사용에 대하여

### ISSUE THREAD

**Issue by seohongpark** [snu-sf-class/PP2015f_TA#62]
과제 3-3 코드를 작성하는데 있어 selfgrader나 library에 정의된 여러가지 유용한 함수들을 그대로 복사하여 써도 되나요?

예를 들어 hw3-3-selfgrader.rkt에 있는

```
(define (det-next-i i j n)
  (if (even? j)
      (if (= n 0) i (+ i 1))
      (if (= n 0) (- i 1) i)
      ))

(define (get-room cur d)
  (let ([i (car cur)] [j (cdr cur)])
    (cond
      [(equal? d 0) (cons (- i 1) j)]
      [(equal? d 1) (cons (det-next-i i j 0) (+ j 1))]
      [(equal? d 2) (cons (det-next-i i j 1) (+ j 1))]
      [(equal? d 3) (cons (+ i 1) j)]
      [(equal? d 4) (cons (det-next-i i j 1) (- j 1))]
      [else (cons (det-next-i i j 0) (- j 1))]
      )
    ))
```

과 같은 부분을 복사하여 hw3-3를 작성하는 데 써도 되는지 여쭤보고 싶습니다.

+

덤으로 30초 시간제한이라는 것은 각 미로당인가요? 아니면 5개의 실행시간을 합친 기준인가요?

++

selfgrader에서 n이 1이면 항상 error가 나는 것 같습니다.

**Comment by kim-yoonseung** [comment]
네. 3-3을 풀기 위해 self grader, library 등에서 코드를 복사해 쓰셔도 됩니다.

시간은 각 미로당 30초입니다.

n=1일 때 문제가 생기는 줄은 예상치 못했습니다. 확인해보겠습니다.
