### ISSUE TITLE
hw3-3 테스트 시행횟수 관련 질문드립니다.

### ISSUE THREAD

**Issue by taehwoi** [snu-sf-class/PP2015f_TA#69]
안녕하세요. 랜덤으로 미로를 구성하게 했을 경우, 확률에 따라서 미로의 난이도가 약간씩 바뀌는 데, 미로를 채점할 때는 어떤 식으로 채점하게 되는 지 궁금합니다. 
1) 여러 번 채점하여 평균내기
2) 여유있는 기준을 두고 기준 이상의 미로는 통과시키기
3) 한 번의 시행결과로 평가하기
만약 3번으로 평가한다면 셀프그레이더의 평가함수를 붙여넣고 일정 수치 미만이면 다시 만들게 한다든지 해야 할 것 같은데 평가가 어떤 식으로 진행될지 알려주시면 감사하겠습니다.

**Comment by kim-yoonseung** [comment]
수치로 줄 세워서 잘라서 채점하기보다는, 수치가 어느 정도 되는 미로들을 골라 그림을 확인하여 점수를 주려고 합니다. 2번에 가까운 것 같고, ~~현재는 한 미로 당 한 번 실행할 생각입니다.~~
한 사이즈의 미로당 여러 번 실행하여 모두 unique가 나올 경우, 평균적인 점수로 걸러내겠습니다.
여러 번 실행하여 모두 unique가 아닌 경우에는 낮은 기준에 맞추어 채점하겠습니다.
