### ISSUE TITLE
selfgrader 실행만으로 점수를 확인할 수 있나요?

### ISSUE THREAD

**Issue by ik1ne** [snu-sf-class/PP2015f_TA#7]
조금 더 자세하게 말하자면, selfgrader에 있는 테스트 케이스를 전부다 통과하면 실제 채점에서도 만점을 받을 수 있을지 궁금합니다.
selfgrader 이외에 자체적으로 만든 테스트 케이스에 대해서도 테스트를 해봐야 할까요?

**Comment by kim-yoonseung** [comment]
숙제 설명에 쓴 대로, 자가 채점기가 실제 테스트에 쓰이는 것은 아닙니다. 따라서 자체적으로 여러 테스트를 해보는 것이 좋겠습니다.
