### ISSUE TITLE
4-1 테스트 질문입니다.

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#70]
두번째 문제의 경우 나와야 하는 vlencode 의 결과는 '(("d" 0) ("c" 1 0) ("b" 1 1 0) ("a" 1 1 1)) 라고 생각합니다.
가장 많이 나오는 문자가 d, c, b, a 순서이기 떄문입니다.

그렇게 해서 (a, b, c, d)가 각각 (3, 4, 5, 6)번 나오므로 계산되어야 할 결과는 

3_3+3_4+2_5+1_6 = 9 + 12 + 10 + 6 = 37 아닌가요?

테스트 코드에서는 36과 비교되는데, 이 경우 나와야 할 vlencode의 결과가 어떤 모습인지 궁금합니다.

세 번째 테스트 케이스의 경우도 마찬가지로 37로 나와야 할 것 같은데, 확인 부탁드립니다.

**Comment by eodmsabc** [comment]
저 경우에는 0 10 110 111보다
00 01 10 11로 부여한 케이스가 전체 길이를 짧게 줄일 수 있고 이 케이스 역시 prefix-free를 만족합니다 그래서 결과가 36으로 나온 것 같네요

**Comment by iKoru** [comment]
그런데 과제 설명 pdf파일을 보면, 다음과 같은 문장이 있습니다.

이번 숙제에서는 "앞겹침 없는"성질을 가지는 크기변동 코드를 만드는 프로그램 vlencode를 작성하는 것입니다.

따라서 vlencode는 크기변동코드, 즉 앞서 설명된 대로 "단어의 사용빈도를 알고 자주 사용되는 단어일수록 짧은 코드를 사용하면, 문장을 표현하는 코드는 더 짧아질 수 있습니다"라는 것을 참고하면 언급해주신것과 같이 크기고정코드는 문제에서 원하는 것이 아니라는 것을 알 수 있습니다.

설마 전체 성능을 보고 둘 중에서 더 짧은 것으로 내놓는 코드를 작성해야 하나요?

**Comment by eodmsabc** [comment]
00 01 10 11을 크기고정코드라고 볼 수도 있지만 '앞겹침 없는'코드로도 볼 수 있습니다
실제 이 네 수 모두 앞부분이 다른 코드가 되지 않으니까요
이 케이스에서는 가장짧은 앞겹침없는 코드를 구했는데 우연히 네 개의 코드길이가 같아진 것 뿐입니다

**Comment by kim-yoonseung** [comment]
eod님의 말씀대로, 단순히 가장 빈번한 단어에 한 자리 코드를 부여하는 식이 아니라, 전체 빈도에 대해서 가장 길이가 짧게 나오는 '앞겹침 없는 코드'를 구해야 합니다.
