### ISSUE TITLE
Racket 내부 라이브러리 사용

### ISSUE THREAD

**Issue by hyunminch** [snu-sf-class/PP2015f_TA#71]
과제 4를 하던 중 궁금한 것 질문 드립니다.

과제에서 sort와 같은 내부 라이브러리를 사용해도 불이익이 없을지 궁금합니다.

**Comment by hyunminch** [comment]
그 외에도 append와 같은 함수도 사용이 가능할까요?

**Comment by kim-yoonseung** [comment]
내부 라이브러리를 사용해도 됩니다.
append는 실습 시간에도 잠깐 등장했었고, 사용이 가능합니다.
