### ISSUE TITLE
4-1 번의 test-case에 대한 질문입니다.

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#75]
안녕하세요. 과제 중에 4-1에 대해서 궁금한 점이 있어서 여쭙니다. 

self-grader 의 case 중에 어떤 문자는 사용빈도가 0인 것이 있었습니다. 이 경우에는 아예 code table에 포함을 시키지 않아야 하는 것인지 궁금합니다.

**Comment by kim-yoonseung** [comment]
~~넣어도/안 넣어도 상관 없을 것입니다.
평가는 코딩 이후 전체 길이를 가지고 하는데, 제일 긴 코드를 부여하더라도 어차피 비중이 0일 것이니까요.~~
방금 코드를 다시 보니 있어야 well-formed인 것 같군요. 빈도가 0인 코드도 필요합니다만 제일 긴 코드를 부여하더라도 비중이 0이니 score는 그대로 나오는 것은 맞습니다.

**Comment by eastskykang** [comment]
@kim-yoonseung 조교님 빠른 답변 감사합니다! 하지만 빈도수가 0인 leaf가 포함되면 tree의 크기가 달라질 소지가 있기 때문에 포함시키지 않는 경우보다 더 긴 코드들이 할당되게 됩니다. 그래서 실제 길이가 좀 더 길게 나타날 수 있는 것 같습니다. 이 부분에 대해서 스펙에 좀 더 구체적인 명시가 필요하다고 느낍니다! well-formed의 문제 같은 경우에는 처음부터 해당 스트링들을 제거하고 허프만 트리를 만들면 해결되는 것 같습니다. 감사합니다.

**Comment by kim-yoonseung** [comment]
그렇군요, 제가 가볍게 생각했었는데 0인 빈도인 코드라도 이것을 포함하느냐 마느냐에 따라 길이가 달라질 수 있네요.
알아보니 매년 빈도 0을 어떻게 처리하는지 기준이 약간 달랐었는데, 이번에는 포함해도 좋고 안 해도 좋습니다.
테스트는 포함 여부에 관계없이 같은 길이가 나오는 경우만 하겠습니다.

**Comment by eastskykang** [comment]
@kim-yoonseung 잘 알겠습니다! 저는 일단 0이하의 빈도수(0 혹은 음수)가 들어오는 경우는 이를 리스트에서 걸러낸 식으로 처리했습니다. 음수 입력이 들어오더라도 특별한 exception 처리는 필요가 없을까요? 

더불어서 이번에 self grader를 보면 빈 리스트가 들어오는 케이스에 대한 테스트 케이스가 있던데 이 경우에는 역시나 빈 테이블을 리턴하는 식으로 처리 하면 되련지요? (처음에는 raise exception 처리 했었는데 테스트 케이스를 보니 빈 테이블을 리턴하게 되어있는 것 같습니다)

**Comment by kim-yoonseung** [comment]
음수는 테스트하지 않을 예정입니다.
빈 리스트 처리는 현재 받으신 self grader가 잘 돌아가면 됩니다. 채점 코드는 self grader와 같은 방식으로 짜여질 것입니다.

**Comment by eastskykang** [comment]
@kim-yoonseung  조교님 감사합니다. 마지막으로 하나만 더 여쭤보겠습니다. 문자가 하나만 입력으로 들어온 경우에는 어떤 식으로 처리를 해야 할까요? 그냥 길이 1짜리 코드 하나로 할당하면 될까요?

**Comment by kim-yoonseung** [comment]
네 그러면 될 것 같습니다.
