### ISSUE TITLE
5-3 의 잘못된 입력

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#84]
5-3에서 말하는 잘못된 입력(타입에는 맞지만 의도치 않은 입력)이라는 것이 어떤 것인지 궁금합니다. 
- 이를테면, fst나 rest, nth-elmt, map, reduce 에 empty list가 들어온 경우를 얘기하는것인지요? 이 부분에 대해서 조금 명확한 정의가 필요한 것 같습니다. 
- 추가로 오늘 교수님께 이 과제와 관련해서 여쭤봤는데 input은 항상 type에 맞게 들어온다고 가정해도 된다고 하셨던 것으로 기억합니다. 
  - 즉 채점시 테스트 케이스에서 tau list 를 받는 함수들의 입력은 항상 tau list가 들어온다고 생각해도 될지 궁금합니다.

**Comment by eastskykang** [comment]
더불어서 한가지 더 질문드립니다. self-grader의 다음 코드를 보면 

```
(define (right-unit? s)
  (case-sum
   (lambda (v) #f)
   (lambda (v) (equal? v '()))
   s))
```

여기서 s는 tau인데 case-sum은 (tau + tau')을 인자로 받게 되어 있습니다. s를 tau+tau' 타입이라고 생각하고 구현 하면 될까요?

**Comment by kim-yoonseung** [comment]
예를 들면 fst는 리스트를 받아서 첫 번째 원소를 줘야 되는데 빈 리스트가 들어오면 어떻게 처리해야 할 지 난감하잖아요? nth-elmt와 같은 경우도 리스트 크기가 3인데 5번째 원소를 달라고 할 경우, 모든 인자가 타입은 맞게 들어왔지만 정상적인 처리가 불가능한 경우가 있겠죠. map, reduce와 같은 경우는 빈 리스트가 들어오는 것도 정상적인 입력입니다.

또한 채점시에는 지금까지 그래왔듯이 언제나 타입에 맞는 입력만을 체크합니다.

self-grader 관련 질문의 경우, 저는 언제나 s에 sum type의 인자가 들어오게만 의도했는데, 혹시 아닌 곳이 있나요?

**Comment by eastskykang** [comment]
@kim-yoonseung  조교님께. 교수님께서 업로드 하신 스펙 메뉴얼에는 (tau + tau') type (sum type)이 아니라 tau type으로 표기가 되어 있습니다! 그래서 제가 혼동했었던 것 같네요. sum type으로 구현하도록 하겠습니다!

**Comment by kim-yoonseung** [comment]
저는 교수님이 업로드하신 문서에서 말씀하신 부분을 못 찾겠는데요, 혹시 어느 부분인지 알려주실 수 있나요?
