### ISSUE TITLE
5-4 array와 tree 구현

### ISSUE THREAD

**Issue by eodmsabc** [snu-sf-class/PP2015f_TA#86]
5-4 과제에서, array로 구현한 벽지와 tree로 구현한 벽지 무늬는
독립적으로 작동이 가능해야 하나요? 아니면
각각의 함수들 중 하나만 구현하고 나머지는 array-to-tree와 tree-to-array를 사용해서 구현해도 되는지 궁금합니다.

예를 들어 rotate-array 는
array-to-tree
rotate-tree
tree-to-array
세 개의 함수로 구현이 가능한데, 이렇게 구현해도 되나요?

**Comment by kim-yoonseung** [comment]
이 문제의 의도가 사실 말씀하신 대로 하는 것입니다.
rotate의 경우는 array 구현에서는 하기 어렵지만 tree 구현에서는 하기 쉬우므로, 적절히 두 구현을 넘나들면서 최대한 편리한 방식을 찾으시면 됩니다.
