### ISSUE TITLE
5-4번에서 glue, rotate, neighbor와 같은 함수의 인풋에 대해서

### ISSUE THREAD

**Issue by iKoru** [snu-sf-class/PP2015f_TA#89]
각 함수들의 타입의 인풋이 form 타입으로 정의되어 있는데요, 

지금 이해하기로는 form 타입이 array+tree 정도의 타입인 것으로 보입니다.

그렇다면 여러개가 인풋으로 들어오는 glue의 경우에는 두 종류가 혼합되어서 들어올 수도 있나요?

**Comment by kim-yoonseung** [comment]
각 함수의 인풋이 form인 경우, array 또는 tree 구현 중 어느 것이라도 들어올 수 있습니다.

glue의 경우는 섞여서 들어와도 잘 동작해야 합니다. 

(참고: 작년의 경우는 한 가지로 통일되어 들어오는 경우만 테스트하였으나, 이는 잘못된 결정이었습니다.)

**Comment by pse1202** [comment]
nw ne se sw가 다른 타입일 수 있다는 뜻인가요?

**Comment by eastskykang** [comment]
interface 함수에서는 그렇다는 말씀이신것 같습니다. 그 외의 함수에는 전부 type to type 의 형태로 함수를 구현하니 interface 함수에서만 유의하면 괜찮을 것 같습니다.

**Comment by eastskykang** [comment]
@kim-yoonseung  조교님 그렇다면 glue 함수의 경우에는 출력은 array 타입이던지 tree 타입이던지 상관이 없는건가요?

**Comment by kim-yoonseung** [comment]
네, glue, rotate 등의 함수는 입력은 둘 중 어떤 구현이든 될 수 있고, 출력은 둘 중 무엇을 해도 좋습니다.

구현이 특정이 된 glue-tree-from-array와 같은 함수는 입력은 정해진 구현의 입력만 들어온다고 가정해도 좋으며, 출력은 정해진 구현으로 출력되어야 합니다.
