### ISSUE TITLE
hw5-4.rkt 예시관련 질문드립니다.

### ISSUE THREAD

**Issue by taehwoi** [snu-sf-class/PP2015f_TA#92]
안녕하세요.
5-4의 주석부분에서 트리로 구현된 타일의 예시로 다음과 같은 타일이 있습니다.

``` racket
 (cons 'tree (list (list 'B 'B 'B 'W) (list 'B 'B 'W 'B) (list 'B 'W 'B 'B) (list 'W 'B 'B 'B)))
 BBBB
 WBBW
 WBBW
 BBBB
```

``` racket
(cons 'tree (list 'B 'B 'W 'B))
BB
BW
```

위의 4칸 타일 예제에 비춰본다면, 16칸 짜리 트리타일 구현은

``` racket
(cons 'tree (list ('tree . (list 'B 'B 'B 'W)) ('tree . (list 'B 'B 'W 'B))('tree . (list 'B 'W 'B 'B))('tree . (list 'W 'B 'B 'B)))
```

처럼 되어야 할 것 같습니다. 
아니면 맨 앞에 트리라고 붙어있기만 하면 내부의 리스트들을 전부 트리로 해석하면 되는 것인가요?
감사합니다.

**Comment by knockLeopard** [comment]
저도 @indiofish 님처럼 생각하는 사람 중 하나인데요, 트리타일 구현은 각각이 모두 새로운 트리이기때문에 @indiofish 님이 적으신대로 구현되어야 하지 않나요?

**Comment by kim-yoonseung** [comment]
tree 구현의 경우 표시(`'tree`)는 앞쪽에 한 번만 나오며, 내부는 모두 tree의 구현방법을 따릅니다. #95 와도 약간 관련이 있겠네요.

트리의 경우 4방향이 새로운 트리가 되야 하지만, form 타입의 tree 구현일 필요까지는 없습니다.

구현에 따라 `'tree` 심볼을 넣었다 뺐다 하는 게 번거로울 수도 있겠습니다만, 중복되는 정보를 줄인다는 측면에서는 이 방법 또한 합리적인 구현이라고 생각합니다.
