### ISSUE TITLE
수업과 직접 연관있는 것은 아니지만 수업홈페이지 링크가 이상한 것 같습니다.

### ISSUE THREAD

**Issue by taehwoi** [snu-sf-class/PP2015f_TA#96]
안녕하세요. 수업 홈페이지 
http://sf.snu.ac.kr/gil.hur/4190.210/15/
에서 Slides & Resources의
Textbook (Translated): [컴퓨터 프로그램의 구조와 해석], 김재우 외, 인사이트, 2007
링크를 누르면 엔씨소프트(...)로 연결됩니다.
수정해주시면 감사하겠습니다.

**Comment by kim-yoonseung** [comment]
감사합니다. 원래 책을 볼 수 있던 springnote라는 곳이 망했나 보네요.

그 사이트는 교수님이 관리하시므로 교수님께 시간 나면 말씀드려보겠습니다.
