### ISSUE TITLE
5-4와 5-5에서 primitive tile 입력에 대해서  

### ISSUE THREAD

**Issue by eastskykang** [snu-sf-class/PP2015f_TA#98]
안녕하세요. 

5-4번의 neighbor 함수와 5-5의 size와 beautiful 함수에 primitive tile 즉 단위 크기의 black 이나 white 타일이 들어오는 경우에는 어떤 값을 출력해야 하는지 궁급합니다. 

neighbor나 size의 경우에는 0을 출력하면 될 것 같은데 beautiful의 경우엔 명시가 필요할 것 같습니다.

**Comment by iKoru** [comment]
beautiful-sym에서 true를 리턴하게끔 될거같긴한데 애매한부분은 있네요ㅠㅠ

**Comment by kim-yoonseung** [comment]
size와 neighbor는 정의상 0이고, beautiful은 대칭이므로 true입니다.
